
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative000
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative001
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative002
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative003
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative004
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative005
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative006
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative007
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative008
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative009
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative010
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative011
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative012
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative013
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative014
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative015
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative016
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative017
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative018
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative019
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative020
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative021
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative022
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative023
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative024
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative025
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative026
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative027
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative028
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative029
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative030
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative031
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative032
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative033
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative034
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative035
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative036
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative037
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative038
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative039
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative040
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative041
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative042
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative043
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative044
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative045
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative046
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative047
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative048
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative049
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative050
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative051
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative052
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative053
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative054
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative055
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative056
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative057
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative058
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative059
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative060
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative061
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative062
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative063
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative064
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative065
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative066
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative067
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative068
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative069
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative070
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative071
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative072
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative073
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative074
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative075
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative076
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative077
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative078
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative079
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative080
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative081
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative082
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative083
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative084
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative085
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative086
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative087
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative088
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative089
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative090
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative091
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative092
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative093
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative094
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative095
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative096
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative097
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative098
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative099
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative100
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative101
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative102
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative103
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative104
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative105
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative106
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative107
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative108
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative109
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative110
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative111
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative112
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative113
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative114
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative115
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative116
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative117
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative118
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative119
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative120
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative121
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative122
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative123
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative124
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative125
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative126
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative127
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative128
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative129
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative130
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative131
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative132
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative133
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative134
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative135
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative136
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative137
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative138
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative139
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative140
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative141
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative142
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative143
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative144
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative145
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative146
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative147
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative148
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative149
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative150
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Negative151
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive000
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive001
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive002
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive003
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive004
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive005
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive006
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive007
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive008
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive009
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive010
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive011
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive012
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive013
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive014
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive015
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive016
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive017
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive018
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive019
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive020
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive021
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive022
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive023
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive024
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive025
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive026
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive027
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive028
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive029
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive030
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive031
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive032
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive033
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive034
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive035
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive036
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive037
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive038
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive039
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive040
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive041
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive042
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive043
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive044
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive045
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive046
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive047
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive048
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive049
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive050
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive051
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive052
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive053
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive054
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive055
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive056
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive057
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive058
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive059
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive060
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive061
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive062
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive063
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive064
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive065
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive066
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive067
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive068
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive069
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive070
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive071
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive072
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive073
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive074
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive075
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive076
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive077
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive078
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive079
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive080
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive081
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive082
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive083
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive084
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive085
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive086
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive087
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive088
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive089
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive090
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive091
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive092
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive093
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive094
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive095
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive096
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive097
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive098
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive099
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive100
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive101
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive102
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive103
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive104
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive105
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive106
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive107
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive108
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive109
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive110
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive111
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive112
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive113
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive114
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive115
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive116
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive117
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive118
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive119
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive120
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive121
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive122
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive123
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive124
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive125
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive126
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive127
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive128
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive129
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive130
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive131
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive132
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive133
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive134
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive135
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive136
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive137
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive138
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive139
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive140
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive141
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive142
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive143
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive144
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive145
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive146
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive147
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive148
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive149
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive150
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive151
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive152
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive153
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive154
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive155
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive156
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive157
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive158
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive159
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive160
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive161
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive162
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive163
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive164
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive165
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive166
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive167
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive168
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive169
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive170
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive171
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive172
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive173
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive174
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive175
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive176
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive177
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive178
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive179
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive180
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive181
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive182
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive183
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive184
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive185
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive186
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive187
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive188
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive189
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive190
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive191
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive192
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive193
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive194
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive195
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive196
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive197
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive198
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive199
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive200
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive201
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive202
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive203
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive204
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive205
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive206
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive207
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive208
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive209
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive210
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive211
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive212
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive213
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive214
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive215
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive216
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive217
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive218
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive219
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive220
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive221
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive222
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive223
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive224
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive225
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive226
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive227
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive228
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive229
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive230
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive231
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive232
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive233
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive234
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive235
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive236
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive237
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive238
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive239
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive240
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive241
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive242
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive243
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive244
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive245
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive246
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive247
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive248
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive249
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive250
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive251
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive252
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive253
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive254
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive255
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive256
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive257
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive258
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive259
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive260
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive261
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive262
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive263
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive264
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive265
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Positive266
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Diagonal000
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Diagonal001
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Diagonal002
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Diagonal003
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Diagonal004
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Diagonal005
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePacketBridges.Diagonal006
import Mathlib.Tactic.FinCases

namespace ConnesRigidity

namespace AffineSymplecticCertificate

private theorem coefficientChunksPrefix
    {α : Type*} (entries : List α) (size count : Nat) :
    ((List.range count).map fun i =>
      (entries.drop (i * size)).take size).flatten =
        entries.take (count * size) := by
  induction count with
  | zero =>
      simp
  | succ count ih =>
      rw [List.range_succ, List.map_append, List.flatten_append, ih]
      simp [Nat.succ_mul, List.take_add]

theorem allNegativePacketTermChunkBridges
    (i : Fin 152) :
    coefficientNegativePacketTermChunk i =
      (negativeEdgeTerms.drop (i * 512)).take
        512 := by
  fin_cases i
  · exact coefficientNegativePacketTermsBridge_000
  · exact coefficientNegativePacketTermsBridge_001
  · exact coefficientNegativePacketTermsBridge_002
  · exact coefficientNegativePacketTermsBridge_003
  · exact coefficientNegativePacketTermsBridge_004
  · exact coefficientNegativePacketTermsBridge_005
  · exact coefficientNegativePacketTermsBridge_006
  · exact coefficientNegativePacketTermsBridge_007
  · exact coefficientNegativePacketTermsBridge_008
  · exact coefficientNegativePacketTermsBridge_009
  · exact coefficientNegativePacketTermsBridge_010
  · exact coefficientNegativePacketTermsBridge_011
  · exact coefficientNegativePacketTermsBridge_012
  · exact coefficientNegativePacketTermsBridge_013
  · exact coefficientNegativePacketTermsBridge_014
  · exact coefficientNegativePacketTermsBridge_015
  · exact coefficientNegativePacketTermsBridge_016
  · exact coefficientNegativePacketTermsBridge_017
  · exact coefficientNegativePacketTermsBridge_018
  · exact coefficientNegativePacketTermsBridge_019
  · exact coefficientNegativePacketTermsBridge_020
  · exact coefficientNegativePacketTermsBridge_021
  · exact coefficientNegativePacketTermsBridge_022
  · exact coefficientNegativePacketTermsBridge_023
  · exact coefficientNegativePacketTermsBridge_024
  · exact coefficientNegativePacketTermsBridge_025
  · exact coefficientNegativePacketTermsBridge_026
  · exact coefficientNegativePacketTermsBridge_027
  · exact coefficientNegativePacketTermsBridge_028
  · exact coefficientNegativePacketTermsBridge_029
  · exact coefficientNegativePacketTermsBridge_030
  · exact coefficientNegativePacketTermsBridge_031
  · exact coefficientNegativePacketTermsBridge_032
  · exact coefficientNegativePacketTermsBridge_033
  · exact coefficientNegativePacketTermsBridge_034
  · exact coefficientNegativePacketTermsBridge_035
  · exact coefficientNegativePacketTermsBridge_036
  · exact coefficientNegativePacketTermsBridge_037
  · exact coefficientNegativePacketTermsBridge_038
  · exact coefficientNegativePacketTermsBridge_039
  · exact coefficientNegativePacketTermsBridge_040
  · exact coefficientNegativePacketTermsBridge_041
  · exact coefficientNegativePacketTermsBridge_042
  · exact coefficientNegativePacketTermsBridge_043
  · exact coefficientNegativePacketTermsBridge_044
  · exact coefficientNegativePacketTermsBridge_045
  · exact coefficientNegativePacketTermsBridge_046
  · exact coefficientNegativePacketTermsBridge_047
  · exact coefficientNegativePacketTermsBridge_048
  · exact coefficientNegativePacketTermsBridge_049
  · exact coefficientNegativePacketTermsBridge_050
  · exact coefficientNegativePacketTermsBridge_051
  · exact coefficientNegativePacketTermsBridge_052
  · exact coefficientNegativePacketTermsBridge_053
  · exact coefficientNegativePacketTermsBridge_054
  · exact coefficientNegativePacketTermsBridge_055
  · exact coefficientNegativePacketTermsBridge_056
  · exact coefficientNegativePacketTermsBridge_057
  · exact coefficientNegativePacketTermsBridge_058
  · exact coefficientNegativePacketTermsBridge_059
  · exact coefficientNegativePacketTermsBridge_060
  · exact coefficientNegativePacketTermsBridge_061
  · exact coefficientNegativePacketTermsBridge_062
  · exact coefficientNegativePacketTermsBridge_063
  · exact coefficientNegativePacketTermsBridge_064
  · exact coefficientNegativePacketTermsBridge_065
  · exact coefficientNegativePacketTermsBridge_066
  · exact coefficientNegativePacketTermsBridge_067
  · exact coefficientNegativePacketTermsBridge_068
  · exact coefficientNegativePacketTermsBridge_069
  · exact coefficientNegativePacketTermsBridge_070
  · exact coefficientNegativePacketTermsBridge_071
  · exact coefficientNegativePacketTermsBridge_072
  · exact coefficientNegativePacketTermsBridge_073
  · exact coefficientNegativePacketTermsBridge_074
  · exact coefficientNegativePacketTermsBridge_075
  · exact coefficientNegativePacketTermsBridge_076
  · exact coefficientNegativePacketTermsBridge_077
  · exact coefficientNegativePacketTermsBridge_078
  · exact coefficientNegativePacketTermsBridge_079
  · exact coefficientNegativePacketTermsBridge_080
  · exact coefficientNegativePacketTermsBridge_081
  · exact coefficientNegativePacketTermsBridge_082
  · exact coefficientNegativePacketTermsBridge_083
  · exact coefficientNegativePacketTermsBridge_084
  · exact coefficientNegativePacketTermsBridge_085
  · exact coefficientNegativePacketTermsBridge_086
  · exact coefficientNegativePacketTermsBridge_087
  · exact coefficientNegativePacketTermsBridge_088
  · exact coefficientNegativePacketTermsBridge_089
  · exact coefficientNegativePacketTermsBridge_090
  · exact coefficientNegativePacketTermsBridge_091
  · exact coefficientNegativePacketTermsBridge_092
  · exact coefficientNegativePacketTermsBridge_093
  · exact coefficientNegativePacketTermsBridge_094
  · exact coefficientNegativePacketTermsBridge_095
  · exact coefficientNegativePacketTermsBridge_096
  · exact coefficientNegativePacketTermsBridge_097
  · exact coefficientNegativePacketTermsBridge_098
  · exact coefficientNegativePacketTermsBridge_099
  · exact coefficientNegativePacketTermsBridge_100
  · exact coefficientNegativePacketTermsBridge_101
  · exact coefficientNegativePacketTermsBridge_102
  · exact coefficientNegativePacketTermsBridge_103
  · exact coefficientNegativePacketTermsBridge_104
  · exact coefficientNegativePacketTermsBridge_105
  · exact coefficientNegativePacketTermsBridge_106
  · exact coefficientNegativePacketTermsBridge_107
  · exact coefficientNegativePacketTermsBridge_108
  · exact coefficientNegativePacketTermsBridge_109
  · exact coefficientNegativePacketTermsBridge_110
  · exact coefficientNegativePacketTermsBridge_111
  · exact coefficientNegativePacketTermsBridge_112
  · exact coefficientNegativePacketTermsBridge_113
  · exact coefficientNegativePacketTermsBridge_114
  · exact coefficientNegativePacketTermsBridge_115
  · exact coefficientNegativePacketTermsBridge_116
  · exact coefficientNegativePacketTermsBridge_117
  · exact coefficientNegativePacketTermsBridge_118
  · exact coefficientNegativePacketTermsBridge_119
  · exact coefficientNegativePacketTermsBridge_120
  · exact coefficientNegativePacketTermsBridge_121
  · exact coefficientNegativePacketTermsBridge_122
  · exact coefficientNegativePacketTermsBridge_123
  · exact coefficientNegativePacketTermsBridge_124
  · exact coefficientNegativePacketTermsBridge_125
  · exact coefficientNegativePacketTermsBridge_126
  · exact coefficientNegativePacketTermsBridge_127
  · exact coefficientNegativePacketTermsBridge_128
  · exact coefficientNegativePacketTermsBridge_129
  · exact coefficientNegativePacketTermsBridge_130
  · exact coefficientNegativePacketTermsBridge_131
  · exact coefficientNegativePacketTermsBridge_132
  · exact coefficientNegativePacketTermsBridge_133
  · exact coefficientNegativePacketTermsBridge_134
  · exact coefficientNegativePacketTermsBridge_135
  · exact coefficientNegativePacketTermsBridge_136
  · exact coefficientNegativePacketTermsBridge_137
  · exact coefficientNegativePacketTermsBridge_138
  · exact coefficientNegativePacketTermsBridge_139
  · exact coefficientNegativePacketTermsBridge_140
  · exact coefficientNegativePacketTermsBridge_141
  · exact coefficientNegativePacketTermsBridge_142
  · exact coefficientNegativePacketTermsBridge_143
  · exact coefficientNegativePacketTermsBridge_144
  · exact coefficientNegativePacketTermsBridge_145
  · exact coefficientNegativePacketTermsBridge_146
  · exact coefficientNegativePacketTermsBridge_147
  · exact coefficientNegativePacketTermsBridge_148
  · exact coefficientNegativePacketTermsBridge_149
  · exact coefficientNegativePacketTermsBridge_150
  · exact coefficientNegativePacketTermsBridge_151

theorem coefficientNegativePacketTermChunks_flatten :
    coefficientNegativePacketTermChunks.flatten = negativeEdgeTerms := by
  unfold coefficientNegativePacketTermChunks
  rw [show
      (List.range 152).map coefficientNegativePacketTermChunk =
        (List.range 152).map (fun i =>
          (negativeEdgeTerms.drop (i * 512)).take
            512) by
    apply List.map_congr_left
    intro i hi
    exact allNegativePacketTermChunkBridges
      ⟨i, List.mem_range.mp hi⟩]
  rw [coefficientChunksPrefix]
  apply List.take_of_length_le
  unfold negativeEdgeTerms
  decide +kernel

theorem allPositivePacketTermChunkBridges
    (i : Fin 267) :
    coefficientPositivePacketTermChunk i =
      (positiveEdgeTerms.drop (i * 576)).take
        576 := by
  fin_cases i
  · exact coefficientPositivePacketTermsBridge_000
  · exact coefficientPositivePacketTermsBridge_001
  · exact coefficientPositivePacketTermsBridge_002
  · exact coefficientPositivePacketTermsBridge_003
  · exact coefficientPositivePacketTermsBridge_004
  · exact coefficientPositivePacketTermsBridge_005
  · exact coefficientPositivePacketTermsBridge_006
  · exact coefficientPositivePacketTermsBridge_007
  · exact coefficientPositivePacketTermsBridge_008
  · exact coefficientPositivePacketTermsBridge_009
  · exact coefficientPositivePacketTermsBridge_010
  · exact coefficientPositivePacketTermsBridge_011
  · exact coefficientPositivePacketTermsBridge_012
  · exact coefficientPositivePacketTermsBridge_013
  · exact coefficientPositivePacketTermsBridge_014
  · exact coefficientPositivePacketTermsBridge_015
  · exact coefficientPositivePacketTermsBridge_016
  · exact coefficientPositivePacketTermsBridge_017
  · exact coefficientPositivePacketTermsBridge_018
  · exact coefficientPositivePacketTermsBridge_019
  · exact coefficientPositivePacketTermsBridge_020
  · exact coefficientPositivePacketTermsBridge_021
  · exact coefficientPositivePacketTermsBridge_022
  · exact coefficientPositivePacketTermsBridge_023
  · exact coefficientPositivePacketTermsBridge_024
  · exact coefficientPositivePacketTermsBridge_025
  · exact coefficientPositivePacketTermsBridge_026
  · exact coefficientPositivePacketTermsBridge_027
  · exact coefficientPositivePacketTermsBridge_028
  · exact coefficientPositivePacketTermsBridge_029
  · exact coefficientPositivePacketTermsBridge_030
  · exact coefficientPositivePacketTermsBridge_031
  · exact coefficientPositivePacketTermsBridge_032
  · exact coefficientPositivePacketTermsBridge_033
  · exact coefficientPositivePacketTermsBridge_034
  · exact coefficientPositivePacketTermsBridge_035
  · exact coefficientPositivePacketTermsBridge_036
  · exact coefficientPositivePacketTermsBridge_037
  · exact coefficientPositivePacketTermsBridge_038
  · exact coefficientPositivePacketTermsBridge_039
  · exact coefficientPositivePacketTermsBridge_040
  · exact coefficientPositivePacketTermsBridge_041
  · exact coefficientPositivePacketTermsBridge_042
  · exact coefficientPositivePacketTermsBridge_043
  · exact coefficientPositivePacketTermsBridge_044
  · exact coefficientPositivePacketTermsBridge_045
  · exact coefficientPositivePacketTermsBridge_046
  · exact coefficientPositivePacketTermsBridge_047
  · exact coefficientPositivePacketTermsBridge_048
  · exact coefficientPositivePacketTermsBridge_049
  · exact coefficientPositivePacketTermsBridge_050
  · exact coefficientPositivePacketTermsBridge_051
  · exact coefficientPositivePacketTermsBridge_052
  · exact coefficientPositivePacketTermsBridge_053
  · exact coefficientPositivePacketTermsBridge_054
  · exact coefficientPositivePacketTermsBridge_055
  · exact coefficientPositivePacketTermsBridge_056
  · exact coefficientPositivePacketTermsBridge_057
  · exact coefficientPositivePacketTermsBridge_058
  · exact coefficientPositivePacketTermsBridge_059
  · exact coefficientPositivePacketTermsBridge_060
  · exact coefficientPositivePacketTermsBridge_061
  · exact coefficientPositivePacketTermsBridge_062
  · exact coefficientPositivePacketTermsBridge_063
  · exact coefficientPositivePacketTermsBridge_064
  · exact coefficientPositivePacketTermsBridge_065
  · exact coefficientPositivePacketTermsBridge_066
  · exact coefficientPositivePacketTermsBridge_067
  · exact coefficientPositivePacketTermsBridge_068
  · exact coefficientPositivePacketTermsBridge_069
  · exact coefficientPositivePacketTermsBridge_070
  · exact coefficientPositivePacketTermsBridge_071
  · exact coefficientPositivePacketTermsBridge_072
  · exact coefficientPositivePacketTermsBridge_073
  · exact coefficientPositivePacketTermsBridge_074
  · exact coefficientPositivePacketTermsBridge_075
  · exact coefficientPositivePacketTermsBridge_076
  · exact coefficientPositivePacketTermsBridge_077
  · exact coefficientPositivePacketTermsBridge_078
  · exact coefficientPositivePacketTermsBridge_079
  · exact coefficientPositivePacketTermsBridge_080
  · exact coefficientPositivePacketTermsBridge_081
  · exact coefficientPositivePacketTermsBridge_082
  · exact coefficientPositivePacketTermsBridge_083
  · exact coefficientPositivePacketTermsBridge_084
  · exact coefficientPositivePacketTermsBridge_085
  · exact coefficientPositivePacketTermsBridge_086
  · exact coefficientPositivePacketTermsBridge_087
  · exact coefficientPositivePacketTermsBridge_088
  · exact coefficientPositivePacketTermsBridge_089
  · exact coefficientPositivePacketTermsBridge_090
  · exact coefficientPositivePacketTermsBridge_091
  · exact coefficientPositivePacketTermsBridge_092
  · exact coefficientPositivePacketTermsBridge_093
  · exact coefficientPositivePacketTermsBridge_094
  · exact coefficientPositivePacketTermsBridge_095
  · exact coefficientPositivePacketTermsBridge_096
  · exact coefficientPositivePacketTermsBridge_097
  · exact coefficientPositivePacketTermsBridge_098
  · exact coefficientPositivePacketTermsBridge_099
  · exact coefficientPositivePacketTermsBridge_100
  · exact coefficientPositivePacketTermsBridge_101
  · exact coefficientPositivePacketTermsBridge_102
  · exact coefficientPositivePacketTermsBridge_103
  · exact coefficientPositivePacketTermsBridge_104
  · exact coefficientPositivePacketTermsBridge_105
  · exact coefficientPositivePacketTermsBridge_106
  · exact coefficientPositivePacketTermsBridge_107
  · exact coefficientPositivePacketTermsBridge_108
  · exact coefficientPositivePacketTermsBridge_109
  · exact coefficientPositivePacketTermsBridge_110
  · exact coefficientPositivePacketTermsBridge_111
  · exact coefficientPositivePacketTermsBridge_112
  · exact coefficientPositivePacketTermsBridge_113
  · exact coefficientPositivePacketTermsBridge_114
  · exact coefficientPositivePacketTermsBridge_115
  · exact coefficientPositivePacketTermsBridge_116
  · exact coefficientPositivePacketTermsBridge_117
  · exact coefficientPositivePacketTermsBridge_118
  · exact coefficientPositivePacketTermsBridge_119
  · exact coefficientPositivePacketTermsBridge_120
  · exact coefficientPositivePacketTermsBridge_121
  · exact coefficientPositivePacketTermsBridge_122
  · exact coefficientPositivePacketTermsBridge_123
  · exact coefficientPositivePacketTermsBridge_124
  · exact coefficientPositivePacketTermsBridge_125
  · exact coefficientPositivePacketTermsBridge_126
  · exact coefficientPositivePacketTermsBridge_127
  · exact coefficientPositivePacketTermsBridge_128
  · exact coefficientPositivePacketTermsBridge_129
  · exact coefficientPositivePacketTermsBridge_130
  · exact coefficientPositivePacketTermsBridge_131
  · exact coefficientPositivePacketTermsBridge_132
  · exact coefficientPositivePacketTermsBridge_133
  · exact coefficientPositivePacketTermsBridge_134
  · exact coefficientPositivePacketTermsBridge_135
  · exact coefficientPositivePacketTermsBridge_136
  · exact coefficientPositivePacketTermsBridge_137
  · exact coefficientPositivePacketTermsBridge_138
  · exact coefficientPositivePacketTermsBridge_139
  · exact coefficientPositivePacketTermsBridge_140
  · exact coefficientPositivePacketTermsBridge_141
  · exact coefficientPositivePacketTermsBridge_142
  · exact coefficientPositivePacketTermsBridge_143
  · exact coefficientPositivePacketTermsBridge_144
  · exact coefficientPositivePacketTermsBridge_145
  · exact coefficientPositivePacketTermsBridge_146
  · exact coefficientPositivePacketTermsBridge_147
  · exact coefficientPositivePacketTermsBridge_148
  · exact coefficientPositivePacketTermsBridge_149
  · exact coefficientPositivePacketTermsBridge_150
  · exact coefficientPositivePacketTermsBridge_151
  · exact coefficientPositivePacketTermsBridge_152
  · exact coefficientPositivePacketTermsBridge_153
  · exact coefficientPositivePacketTermsBridge_154
  · exact coefficientPositivePacketTermsBridge_155
  · exact coefficientPositivePacketTermsBridge_156
  · exact coefficientPositivePacketTermsBridge_157
  · exact coefficientPositivePacketTermsBridge_158
  · exact coefficientPositivePacketTermsBridge_159
  · exact coefficientPositivePacketTermsBridge_160
  · exact coefficientPositivePacketTermsBridge_161
  · exact coefficientPositivePacketTermsBridge_162
  · exact coefficientPositivePacketTermsBridge_163
  · exact coefficientPositivePacketTermsBridge_164
  · exact coefficientPositivePacketTermsBridge_165
  · exact coefficientPositivePacketTermsBridge_166
  · exact coefficientPositivePacketTermsBridge_167
  · exact coefficientPositivePacketTermsBridge_168
  · exact coefficientPositivePacketTermsBridge_169
  · exact coefficientPositivePacketTermsBridge_170
  · exact coefficientPositivePacketTermsBridge_171
  · exact coefficientPositivePacketTermsBridge_172
  · exact coefficientPositivePacketTermsBridge_173
  · exact coefficientPositivePacketTermsBridge_174
  · exact coefficientPositivePacketTermsBridge_175
  · exact coefficientPositivePacketTermsBridge_176
  · exact coefficientPositivePacketTermsBridge_177
  · exact coefficientPositivePacketTermsBridge_178
  · exact coefficientPositivePacketTermsBridge_179
  · exact coefficientPositivePacketTermsBridge_180
  · exact coefficientPositivePacketTermsBridge_181
  · exact coefficientPositivePacketTermsBridge_182
  · exact coefficientPositivePacketTermsBridge_183
  · exact coefficientPositivePacketTermsBridge_184
  · exact coefficientPositivePacketTermsBridge_185
  · exact coefficientPositivePacketTermsBridge_186
  · exact coefficientPositivePacketTermsBridge_187
  · exact coefficientPositivePacketTermsBridge_188
  · exact coefficientPositivePacketTermsBridge_189
  · exact coefficientPositivePacketTermsBridge_190
  · exact coefficientPositivePacketTermsBridge_191
  · exact coefficientPositivePacketTermsBridge_192
  · exact coefficientPositivePacketTermsBridge_193
  · exact coefficientPositivePacketTermsBridge_194
  · exact coefficientPositivePacketTermsBridge_195
  · exact coefficientPositivePacketTermsBridge_196
  · exact coefficientPositivePacketTermsBridge_197
  · exact coefficientPositivePacketTermsBridge_198
  · exact coefficientPositivePacketTermsBridge_199
  · exact coefficientPositivePacketTermsBridge_200
  · exact coefficientPositivePacketTermsBridge_201
  · exact coefficientPositivePacketTermsBridge_202
  · exact coefficientPositivePacketTermsBridge_203
  · exact coefficientPositivePacketTermsBridge_204
  · exact coefficientPositivePacketTermsBridge_205
  · exact coefficientPositivePacketTermsBridge_206
  · exact coefficientPositivePacketTermsBridge_207
  · exact coefficientPositivePacketTermsBridge_208
  · exact coefficientPositivePacketTermsBridge_209
  · exact coefficientPositivePacketTermsBridge_210
  · exact coefficientPositivePacketTermsBridge_211
  · exact coefficientPositivePacketTermsBridge_212
  · exact coefficientPositivePacketTermsBridge_213
  · exact coefficientPositivePacketTermsBridge_214
  · exact coefficientPositivePacketTermsBridge_215
  · exact coefficientPositivePacketTermsBridge_216
  · exact coefficientPositivePacketTermsBridge_217
  · exact coefficientPositivePacketTermsBridge_218
  · exact coefficientPositivePacketTermsBridge_219
  · exact coefficientPositivePacketTermsBridge_220
  · exact coefficientPositivePacketTermsBridge_221
  · exact coefficientPositivePacketTermsBridge_222
  · exact coefficientPositivePacketTermsBridge_223
  · exact coefficientPositivePacketTermsBridge_224
  · exact coefficientPositivePacketTermsBridge_225
  · exact coefficientPositivePacketTermsBridge_226
  · exact coefficientPositivePacketTermsBridge_227
  · exact coefficientPositivePacketTermsBridge_228
  · exact coefficientPositivePacketTermsBridge_229
  · exact coefficientPositivePacketTermsBridge_230
  · exact coefficientPositivePacketTermsBridge_231
  · exact coefficientPositivePacketTermsBridge_232
  · exact coefficientPositivePacketTermsBridge_233
  · exact coefficientPositivePacketTermsBridge_234
  · exact coefficientPositivePacketTermsBridge_235
  · exact coefficientPositivePacketTermsBridge_236
  · exact coefficientPositivePacketTermsBridge_237
  · exact coefficientPositivePacketTermsBridge_238
  · exact coefficientPositivePacketTermsBridge_239
  · exact coefficientPositivePacketTermsBridge_240
  · exact coefficientPositivePacketTermsBridge_241
  · exact coefficientPositivePacketTermsBridge_242
  · exact coefficientPositivePacketTermsBridge_243
  · exact coefficientPositivePacketTermsBridge_244
  · exact coefficientPositivePacketTermsBridge_245
  · exact coefficientPositivePacketTermsBridge_246
  · exact coefficientPositivePacketTermsBridge_247
  · exact coefficientPositivePacketTermsBridge_248
  · exact coefficientPositivePacketTermsBridge_249
  · exact coefficientPositivePacketTermsBridge_250
  · exact coefficientPositivePacketTermsBridge_251
  · exact coefficientPositivePacketTermsBridge_252
  · exact coefficientPositivePacketTermsBridge_253
  · exact coefficientPositivePacketTermsBridge_254
  · exact coefficientPositivePacketTermsBridge_255
  · exact coefficientPositivePacketTermsBridge_256
  · exact coefficientPositivePacketTermsBridge_257
  · exact coefficientPositivePacketTermsBridge_258
  · exact coefficientPositivePacketTermsBridge_259
  · exact coefficientPositivePacketTermsBridge_260
  · exact coefficientPositivePacketTermsBridge_261
  · exact coefficientPositivePacketTermsBridge_262
  · exact coefficientPositivePacketTermsBridge_263
  · exact coefficientPositivePacketTermsBridge_264
  · exact coefficientPositivePacketTermsBridge_265
  · exact coefficientPositivePacketTermsBridge_266

theorem coefficientPositivePacketTermChunks_flatten :
    coefficientPositivePacketTermChunks.flatten = positiveEdgeTerms := by
  unfold coefficientPositivePacketTermChunks
  rw [show
      (List.range 267).map coefficientPositivePacketTermChunk =
        (List.range 267).map (fun i =>
          (positiveEdgeTerms.drop (i * 576)).take
            576) by
    apply List.map_congr_left
    intro i hi
    exact allPositivePacketTermChunkBridges
      ⟨i, List.mem_range.mp hi⟩]
  rw [coefficientChunksPrefix]
  apply List.take_of_length_le
  unfold positiveEdgeTerms
  decide +kernel

theorem allDiagonalPacketTermChunkBridges
    (i : Fin 7) :
    coefficientDiagonalPacketTermChunk i =
      (diagonalTerms.drop (i * 256)).take
        256 := by
  fin_cases i
  · exact coefficientDiagonalPacketTermsBridge_000
  · exact coefficientDiagonalPacketTermsBridge_001
  · exact coefficientDiagonalPacketTermsBridge_002
  · exact coefficientDiagonalPacketTermsBridge_003
  · exact coefficientDiagonalPacketTermsBridge_004
  · exact coefficientDiagonalPacketTermsBridge_005
  · exact coefficientDiagonalPacketTermsBridge_006

theorem coefficientDiagonalPacketTermChunks_flatten :
    coefficientDiagonalPacketTermChunks.flatten = diagonalTerms := by
  unfold coefficientDiagonalPacketTermChunks
  rw [show
      (List.range 7).map coefficientDiagonalPacketTermChunk =
        (List.range 7).map (fun i =>
          (diagonalTerms.drop (i * 256)).take
            256) by
    apply List.map_congr_left
    intro i hi
    exact allDiagonalPacketTermChunkBridges
      ⟨i, List.mem_range.mp hi⟩]
  rw [coefficientChunksPrefix]
  apply List.take_of_length_le
  unfold diagonalTerms
  decide +kernel

end AffineSymplecticCertificate

end ConnesRigidity
