


import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative000
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative001
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative002
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative003
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative004
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative005
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative006
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative007
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative008
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative009
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative010
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative011
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative012
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative013
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative014
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative015
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative016
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative017
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative018
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative019
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative020
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative021
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative022
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative023
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative024
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative025
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative026
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative027
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative028
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative029
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative030
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative031
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative032
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative033
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative034
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative035
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative036
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative037
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative038
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative039
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative040
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative041
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative042
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative043
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative044
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative045
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative046
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative047
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative048
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative049
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative050
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative051
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative052
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative053
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative054
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative055
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative056
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative057
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative058
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative059
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative060
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative061
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative062
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative063
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative064
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative065
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative066
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative067
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative068
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative069
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative070
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative071
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative072
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative073
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative074
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative075
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative076
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative077
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative078
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative079
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative080
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative081
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative082
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative083
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative084
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative085
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative086
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative087
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative088
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative089
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative090
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative091
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative092
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative093
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative094
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative095
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative096
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative097
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative098
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative099
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative100
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative101
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative102
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative103
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative104
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative105
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative106
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative107
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative108
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative109
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative110
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative111
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative112
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative113
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative114
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative115
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative116
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative117
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative118
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative119
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative120
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative121
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative122
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative123
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative124
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative125
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative126
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative127
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative128
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative129
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative130
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative131
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative132
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative133
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative134
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative135
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative136
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative137
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative138
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative139
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative140
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative141
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative142
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative143
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative144
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative145
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative146
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative147
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative148
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative149
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative150
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Negative151
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive000
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive001
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive002
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive003
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive004
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive005
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive006
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive007
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive008
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive009
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive010
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive011
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive012
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive013
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive014
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive015
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive016
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive017
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive018
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive019
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive020
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive021
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive022
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive023
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive024
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive025
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive026
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive027
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive028
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive029
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive030
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive031
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive032
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive033
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive034
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive035
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive036
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive037
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive038
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive039
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive040
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive041
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive042
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive043
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive044
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive045
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive046
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive047
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive048
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive049
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive050
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive051
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive052
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive053
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive054
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive055
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive056
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive057
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive058
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive059
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive060
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive061
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive062
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive063
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive064
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive065
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive066
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive067
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive068
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive069
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive070
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive071
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive072
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive073
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive074
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive075
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive076
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive077
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive078
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive079
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive080
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive081
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive082
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive083
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive084
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive085
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive086
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive087
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive088
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive089
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive090
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive091
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive092
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive093
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive094
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive095
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive096
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive097
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive098
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive099
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive100
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive101
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive102
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive103
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive104
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive105
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive106
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive107
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive108
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive109
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive110
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive111
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive112
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive113
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive114
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive115
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive116
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive117
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive118
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive119
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive120
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive121
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive122
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive123
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive124
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive125
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive126
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive127
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive128
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive129
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive130
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive131
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive132
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive133
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive134
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive135
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive136
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive137
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive138
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive139
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive140
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive141
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive142
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive143
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive144
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive145
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive146
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive147
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive148
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive149
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive150
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive151
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive152
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive153
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive154
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive155
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive156
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive157
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive158
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive159
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive160
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive161
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive162
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive163
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive164
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive165
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive166
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive167
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive168
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive169
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive170
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive171
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive172
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive173
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive174
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive175
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive176
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive177
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive178
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive179
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive180
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive181
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive182
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive183
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive184
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive185
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive186
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive187
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive188
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive189
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive190
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive191
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive192
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive193
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive194
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive195
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive196
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive197
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive198
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive199
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive200
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive201
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive202
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive203
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive204
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive205
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive206
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive207
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive208
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive209
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive210
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive211
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive212
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive213
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive214
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive215
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive216
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive217
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive218
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive219
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive220
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive221
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive222
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive223
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive224
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive225
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive226
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive227
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive228
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive229
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive230
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive231
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive232
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive233
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive234
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive235
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive236
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive237
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive238
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive239
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive240
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive241
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive242
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive243
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive244
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive245
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive246
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive247
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive248
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive249
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive250
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive251
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive252
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive253
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive254
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive255
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive256
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive257
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive258
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive259
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive260
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive261
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive262
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive263
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive264
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive265
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Positive266
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Diagonal000
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Diagonal001
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Diagonal002
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Diagonal003
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Diagonal004
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Diagonal005
import ConnesRigidity.PropertyTExactCertificateCoefficientEdgePackets.Diagonal006







namespace ConnesRigidity

namespace AffineSymplecticCertificate


noncomputable def coefficientNegativePacketRowChunk : Nat → List (List Int)
  | 0 => coefficientNegativePacketRows000
  | 1 => coefficientNegativePacketRows001
  | 2 => coefficientNegativePacketRows002
  | 3 => coefficientNegativePacketRows003
  | 4 => coefficientNegativePacketRows004
  | 5 => coefficientNegativePacketRows005
  | 6 => coefficientNegativePacketRows006
  | 7 => coefficientNegativePacketRows007
  | 8 => coefficientNegativePacketRows008
  | 9 => coefficientNegativePacketRows009
  | 10 => coefficientNegativePacketRows010
  | 11 => coefficientNegativePacketRows011
  | 12 => coefficientNegativePacketRows012
  | 13 => coefficientNegativePacketRows013
  | 14 => coefficientNegativePacketRows014
  | 15 => coefficientNegativePacketRows015
  | 16 => coefficientNegativePacketRows016
  | 17 => coefficientNegativePacketRows017
  | 18 => coefficientNegativePacketRows018
  | 19 => coefficientNegativePacketRows019
  | 20 => coefficientNegativePacketRows020
  | 21 => coefficientNegativePacketRows021
  | 22 => coefficientNegativePacketRows022
  | 23 => coefficientNegativePacketRows023
  | 24 => coefficientNegativePacketRows024
  | 25 => coefficientNegativePacketRows025
  | 26 => coefficientNegativePacketRows026
  | 27 => coefficientNegativePacketRows027
  | 28 => coefficientNegativePacketRows028
  | 29 => coefficientNegativePacketRows029
  | 30 => coefficientNegativePacketRows030
  | 31 => coefficientNegativePacketRows031
  | 32 => coefficientNegativePacketRows032
  | 33 => coefficientNegativePacketRows033
  | 34 => coefficientNegativePacketRows034
  | 35 => coefficientNegativePacketRows035
  | 36 => coefficientNegativePacketRows036
  | 37 => coefficientNegativePacketRows037
  | 38 => coefficientNegativePacketRows038
  | 39 => coefficientNegativePacketRows039
  | 40 => coefficientNegativePacketRows040
  | 41 => coefficientNegativePacketRows041
  | 42 => coefficientNegativePacketRows042
  | 43 => coefficientNegativePacketRows043
  | 44 => coefficientNegativePacketRows044
  | 45 => coefficientNegativePacketRows045
  | 46 => coefficientNegativePacketRows046
  | 47 => coefficientNegativePacketRows047
  | 48 => coefficientNegativePacketRows048
  | 49 => coefficientNegativePacketRows049
  | 50 => coefficientNegativePacketRows050
  | 51 => coefficientNegativePacketRows051
  | 52 => coefficientNegativePacketRows052
  | 53 => coefficientNegativePacketRows053
  | 54 => coefficientNegativePacketRows054
  | 55 => coefficientNegativePacketRows055
  | 56 => coefficientNegativePacketRows056
  | 57 => coefficientNegativePacketRows057
  | 58 => coefficientNegativePacketRows058
  | 59 => coefficientNegativePacketRows059
  | 60 => coefficientNegativePacketRows060
  | 61 => coefficientNegativePacketRows061
  | 62 => coefficientNegativePacketRows062
  | 63 => coefficientNegativePacketRows063
  | 64 => coefficientNegativePacketRows064
  | 65 => coefficientNegativePacketRows065
  | 66 => coefficientNegativePacketRows066
  | 67 => coefficientNegativePacketRows067
  | 68 => coefficientNegativePacketRows068
  | 69 => coefficientNegativePacketRows069
  | 70 => coefficientNegativePacketRows070
  | 71 => coefficientNegativePacketRows071
  | 72 => coefficientNegativePacketRows072
  | 73 => coefficientNegativePacketRows073
  | 74 => coefficientNegativePacketRows074
  | 75 => coefficientNegativePacketRows075
  | 76 => coefficientNegativePacketRows076
  | 77 => coefficientNegativePacketRows077
  | 78 => coefficientNegativePacketRows078
  | 79 => coefficientNegativePacketRows079
  | 80 => coefficientNegativePacketRows080
  | 81 => coefficientNegativePacketRows081
  | 82 => coefficientNegativePacketRows082
  | 83 => coefficientNegativePacketRows083
  | 84 => coefficientNegativePacketRows084
  | 85 => coefficientNegativePacketRows085
  | 86 => coefficientNegativePacketRows086
  | 87 => coefficientNegativePacketRows087
  | 88 => coefficientNegativePacketRows088
  | 89 => coefficientNegativePacketRows089
  | 90 => coefficientNegativePacketRows090
  | 91 => coefficientNegativePacketRows091
  | 92 => coefficientNegativePacketRows092
  | 93 => coefficientNegativePacketRows093
  | 94 => coefficientNegativePacketRows094
  | 95 => coefficientNegativePacketRows095
  | 96 => coefficientNegativePacketRows096
  | 97 => coefficientNegativePacketRows097
  | 98 => coefficientNegativePacketRows098
  | 99 => coefficientNegativePacketRows099
  | 100 => coefficientNegativePacketRows100
  | 101 => coefficientNegativePacketRows101
  | 102 => coefficientNegativePacketRows102
  | 103 => coefficientNegativePacketRows103
  | 104 => coefficientNegativePacketRows104
  | 105 => coefficientNegativePacketRows105
  | 106 => coefficientNegativePacketRows106
  | 107 => coefficientNegativePacketRows107
  | 108 => coefficientNegativePacketRows108
  | 109 => coefficientNegativePacketRows109
  | 110 => coefficientNegativePacketRows110
  | 111 => coefficientNegativePacketRows111
  | 112 => coefficientNegativePacketRows112
  | 113 => coefficientNegativePacketRows113
  | 114 => coefficientNegativePacketRows114
  | 115 => coefficientNegativePacketRows115
  | 116 => coefficientNegativePacketRows116
  | 117 => coefficientNegativePacketRows117
  | 118 => coefficientNegativePacketRows118
  | 119 => coefficientNegativePacketRows119
  | 120 => coefficientNegativePacketRows120
  | 121 => coefficientNegativePacketRows121
  | 122 => coefficientNegativePacketRows122
  | 123 => coefficientNegativePacketRows123
  | 124 => coefficientNegativePacketRows124
  | 125 => coefficientNegativePacketRows125
  | 126 => coefficientNegativePacketRows126
  | 127 => coefficientNegativePacketRows127
  | 128 => coefficientNegativePacketRows128
  | 129 => coefficientNegativePacketRows129
  | 130 => coefficientNegativePacketRows130
  | 131 => coefficientNegativePacketRows131
  | 132 => coefficientNegativePacketRows132
  | 133 => coefficientNegativePacketRows133
  | 134 => coefficientNegativePacketRows134
  | 135 => coefficientNegativePacketRows135
  | 136 => coefficientNegativePacketRows136
  | 137 => coefficientNegativePacketRows137
  | 138 => coefficientNegativePacketRows138
  | 139 => coefficientNegativePacketRows139
  | 140 => coefficientNegativePacketRows140
  | 141 => coefficientNegativePacketRows141
  | 142 => coefficientNegativePacketRows142
  | 143 => coefficientNegativePacketRows143
  | 144 => coefficientNegativePacketRows144
  | 145 => coefficientNegativePacketRows145
  | 146 => coefficientNegativePacketRows146
  | 147 => coefficientNegativePacketRows147
  | 148 => coefficientNegativePacketRows148
  | 149 => coefficientNegativePacketRows149
  | 150 => coefficientNegativePacketRows150
  | 151 => coefficientNegativePacketRows151
  | _ => []


noncomputable def coefficientNegativePacketTermChunk : Nat → List (IntegerTableTerm 73033)
  | 0 => coefficientNegativePacketTerms000
  | 1 => coefficientNegativePacketTerms001
  | 2 => coefficientNegativePacketTerms002
  | 3 => coefficientNegativePacketTerms003
  | 4 => coefficientNegativePacketTerms004
  | 5 => coefficientNegativePacketTerms005
  | 6 => coefficientNegativePacketTerms006
  | 7 => coefficientNegativePacketTerms007
  | 8 => coefficientNegativePacketTerms008
  | 9 => coefficientNegativePacketTerms009
  | 10 => coefficientNegativePacketTerms010
  | 11 => coefficientNegativePacketTerms011
  | 12 => coefficientNegativePacketTerms012
  | 13 => coefficientNegativePacketTerms013
  | 14 => coefficientNegativePacketTerms014
  | 15 => coefficientNegativePacketTerms015
  | 16 => coefficientNegativePacketTerms016
  | 17 => coefficientNegativePacketTerms017
  | 18 => coefficientNegativePacketTerms018
  | 19 => coefficientNegativePacketTerms019
  | 20 => coefficientNegativePacketTerms020
  | 21 => coefficientNegativePacketTerms021
  | 22 => coefficientNegativePacketTerms022
  | 23 => coefficientNegativePacketTerms023
  | 24 => coefficientNegativePacketTerms024
  | 25 => coefficientNegativePacketTerms025
  | 26 => coefficientNegativePacketTerms026
  | 27 => coefficientNegativePacketTerms027
  | 28 => coefficientNegativePacketTerms028
  | 29 => coefficientNegativePacketTerms029
  | 30 => coefficientNegativePacketTerms030
  | 31 => coefficientNegativePacketTerms031
  | 32 => coefficientNegativePacketTerms032
  | 33 => coefficientNegativePacketTerms033
  | 34 => coefficientNegativePacketTerms034
  | 35 => coefficientNegativePacketTerms035
  | 36 => coefficientNegativePacketTerms036
  | 37 => coefficientNegativePacketTerms037
  | 38 => coefficientNegativePacketTerms038
  | 39 => coefficientNegativePacketTerms039
  | 40 => coefficientNegativePacketTerms040
  | 41 => coefficientNegativePacketTerms041
  | 42 => coefficientNegativePacketTerms042
  | 43 => coefficientNegativePacketTerms043
  | 44 => coefficientNegativePacketTerms044
  | 45 => coefficientNegativePacketTerms045
  | 46 => coefficientNegativePacketTerms046
  | 47 => coefficientNegativePacketTerms047
  | 48 => coefficientNegativePacketTerms048
  | 49 => coefficientNegativePacketTerms049
  | 50 => coefficientNegativePacketTerms050
  | 51 => coefficientNegativePacketTerms051
  | 52 => coefficientNegativePacketTerms052
  | 53 => coefficientNegativePacketTerms053
  | 54 => coefficientNegativePacketTerms054
  | 55 => coefficientNegativePacketTerms055
  | 56 => coefficientNegativePacketTerms056
  | 57 => coefficientNegativePacketTerms057
  | 58 => coefficientNegativePacketTerms058
  | 59 => coefficientNegativePacketTerms059
  | 60 => coefficientNegativePacketTerms060
  | 61 => coefficientNegativePacketTerms061
  | 62 => coefficientNegativePacketTerms062
  | 63 => coefficientNegativePacketTerms063
  | 64 => coefficientNegativePacketTerms064
  | 65 => coefficientNegativePacketTerms065
  | 66 => coefficientNegativePacketTerms066
  | 67 => coefficientNegativePacketTerms067
  | 68 => coefficientNegativePacketTerms068
  | 69 => coefficientNegativePacketTerms069
  | 70 => coefficientNegativePacketTerms070
  | 71 => coefficientNegativePacketTerms071
  | 72 => coefficientNegativePacketTerms072
  | 73 => coefficientNegativePacketTerms073
  | 74 => coefficientNegativePacketTerms074
  | 75 => coefficientNegativePacketTerms075
  | 76 => coefficientNegativePacketTerms076
  | 77 => coefficientNegativePacketTerms077
  | 78 => coefficientNegativePacketTerms078
  | 79 => coefficientNegativePacketTerms079
  | 80 => coefficientNegativePacketTerms080
  | 81 => coefficientNegativePacketTerms081
  | 82 => coefficientNegativePacketTerms082
  | 83 => coefficientNegativePacketTerms083
  | 84 => coefficientNegativePacketTerms084
  | 85 => coefficientNegativePacketTerms085
  | 86 => coefficientNegativePacketTerms086
  | 87 => coefficientNegativePacketTerms087
  | 88 => coefficientNegativePacketTerms088
  | 89 => coefficientNegativePacketTerms089
  | 90 => coefficientNegativePacketTerms090
  | 91 => coefficientNegativePacketTerms091
  | 92 => coefficientNegativePacketTerms092
  | 93 => coefficientNegativePacketTerms093
  | 94 => coefficientNegativePacketTerms094
  | 95 => coefficientNegativePacketTerms095
  | 96 => coefficientNegativePacketTerms096
  | 97 => coefficientNegativePacketTerms097
  | 98 => coefficientNegativePacketTerms098
  | 99 => coefficientNegativePacketTerms099
  | 100 => coefficientNegativePacketTerms100
  | 101 => coefficientNegativePacketTerms101
  | 102 => coefficientNegativePacketTerms102
  | 103 => coefficientNegativePacketTerms103
  | 104 => coefficientNegativePacketTerms104
  | 105 => coefficientNegativePacketTerms105
  | 106 => coefficientNegativePacketTerms106
  | 107 => coefficientNegativePacketTerms107
  | 108 => coefficientNegativePacketTerms108
  | 109 => coefficientNegativePacketTerms109
  | 110 => coefficientNegativePacketTerms110
  | 111 => coefficientNegativePacketTerms111
  | 112 => coefficientNegativePacketTerms112
  | 113 => coefficientNegativePacketTerms113
  | 114 => coefficientNegativePacketTerms114
  | 115 => coefficientNegativePacketTerms115
  | 116 => coefficientNegativePacketTerms116
  | 117 => coefficientNegativePacketTerms117
  | 118 => coefficientNegativePacketTerms118
  | 119 => coefficientNegativePacketTerms119
  | 120 => coefficientNegativePacketTerms120
  | 121 => coefficientNegativePacketTerms121
  | 122 => coefficientNegativePacketTerms122
  | 123 => coefficientNegativePacketTerms123
  | 124 => coefficientNegativePacketTerms124
  | 125 => coefficientNegativePacketTerms125
  | 126 => coefficientNegativePacketTerms126
  | 127 => coefficientNegativePacketTerms127
  | 128 => coefficientNegativePacketTerms128
  | 129 => coefficientNegativePacketTerms129
  | 130 => coefficientNegativePacketTerms130
  | 131 => coefficientNegativePacketTerms131
  | 132 => coefficientNegativePacketTerms132
  | 133 => coefficientNegativePacketTerms133
  | 134 => coefficientNegativePacketTerms134
  | 135 => coefficientNegativePacketTerms135
  | 136 => coefficientNegativePacketTerms136
  | 137 => coefficientNegativePacketTerms137
  | 138 => coefficientNegativePacketTerms138
  | 139 => coefficientNegativePacketTerms139
  | 140 => coefficientNegativePacketTerms140
  | 141 => coefficientNegativePacketTerms141
  | 142 => coefficientNegativePacketTerms142
  | 143 => coefficientNegativePacketTerms143
  | 144 => coefficientNegativePacketTerms144
  | 145 => coefficientNegativePacketTerms145
  | 146 => coefficientNegativePacketTerms146
  | 147 => coefficientNegativePacketTerms147
  | 148 => coefficientNegativePacketTerms148
  | 149 => coefficientNegativePacketTerms149
  | 150 => coefficientNegativePacketTerms150
  | 151 => coefficientNegativePacketTerms151
  | _ => []

noncomputable def coefficientNegativePacketRowChunks : List (List (List Int)) :=
  (List.range 152).map coefficientNegativePacketRowChunk

noncomputable def coefficientNegativePacketTermChunks :
    List (List (IntegerTableTerm 73033)) :=
  (List.range 152).map coefficientNegativePacketTermChunk


noncomputable def coefficientPositivePacketRowChunk : Nat → List (List Int)
  | 0 => coefficientPositivePacketRows000
  | 1 => coefficientPositivePacketRows001
  | 2 => coefficientPositivePacketRows002
  | 3 => coefficientPositivePacketRows003
  | 4 => coefficientPositivePacketRows004
  | 5 => coefficientPositivePacketRows005
  | 6 => coefficientPositivePacketRows006
  | 7 => coefficientPositivePacketRows007
  | 8 => coefficientPositivePacketRows008
  | 9 => coefficientPositivePacketRows009
  | 10 => coefficientPositivePacketRows010
  | 11 => coefficientPositivePacketRows011
  | 12 => coefficientPositivePacketRows012
  | 13 => coefficientPositivePacketRows013
  | 14 => coefficientPositivePacketRows014
  | 15 => coefficientPositivePacketRows015
  | 16 => coefficientPositivePacketRows016
  | 17 => coefficientPositivePacketRows017
  | 18 => coefficientPositivePacketRows018
  | 19 => coefficientPositivePacketRows019
  | 20 => coefficientPositivePacketRows020
  | 21 => coefficientPositivePacketRows021
  | 22 => coefficientPositivePacketRows022
  | 23 => coefficientPositivePacketRows023
  | 24 => coefficientPositivePacketRows024
  | 25 => coefficientPositivePacketRows025
  | 26 => coefficientPositivePacketRows026
  | 27 => coefficientPositivePacketRows027
  | 28 => coefficientPositivePacketRows028
  | 29 => coefficientPositivePacketRows029
  | 30 => coefficientPositivePacketRows030
  | 31 => coefficientPositivePacketRows031
  | 32 => coefficientPositivePacketRows032
  | 33 => coefficientPositivePacketRows033
  | 34 => coefficientPositivePacketRows034
  | 35 => coefficientPositivePacketRows035
  | 36 => coefficientPositivePacketRows036
  | 37 => coefficientPositivePacketRows037
  | 38 => coefficientPositivePacketRows038
  | 39 => coefficientPositivePacketRows039
  | 40 => coefficientPositivePacketRows040
  | 41 => coefficientPositivePacketRows041
  | 42 => coefficientPositivePacketRows042
  | 43 => coefficientPositivePacketRows043
  | 44 => coefficientPositivePacketRows044
  | 45 => coefficientPositivePacketRows045
  | 46 => coefficientPositivePacketRows046
  | 47 => coefficientPositivePacketRows047
  | 48 => coefficientPositivePacketRows048
  | 49 => coefficientPositivePacketRows049
  | 50 => coefficientPositivePacketRows050
  | 51 => coefficientPositivePacketRows051
  | 52 => coefficientPositivePacketRows052
  | 53 => coefficientPositivePacketRows053
  | 54 => coefficientPositivePacketRows054
  | 55 => coefficientPositivePacketRows055
  | 56 => coefficientPositivePacketRows056
  | 57 => coefficientPositivePacketRows057
  | 58 => coefficientPositivePacketRows058
  | 59 => coefficientPositivePacketRows059
  | 60 => coefficientPositivePacketRows060
  | 61 => coefficientPositivePacketRows061
  | 62 => coefficientPositivePacketRows062
  | 63 => coefficientPositivePacketRows063
  | 64 => coefficientPositivePacketRows064
  | 65 => coefficientPositivePacketRows065
  | 66 => coefficientPositivePacketRows066
  | 67 => coefficientPositivePacketRows067
  | 68 => coefficientPositivePacketRows068
  | 69 => coefficientPositivePacketRows069
  | 70 => coefficientPositivePacketRows070
  | 71 => coefficientPositivePacketRows071
  | 72 => coefficientPositivePacketRows072
  | 73 => coefficientPositivePacketRows073
  | 74 => coefficientPositivePacketRows074
  | 75 => coefficientPositivePacketRows075
  | 76 => coefficientPositivePacketRows076
  | 77 => coefficientPositivePacketRows077
  | 78 => coefficientPositivePacketRows078
  | 79 => coefficientPositivePacketRows079
  | 80 => coefficientPositivePacketRows080
  | 81 => coefficientPositivePacketRows081
  | 82 => coefficientPositivePacketRows082
  | 83 => coefficientPositivePacketRows083
  | 84 => coefficientPositivePacketRows084
  | 85 => coefficientPositivePacketRows085
  | 86 => coefficientPositivePacketRows086
  | 87 => coefficientPositivePacketRows087
  | 88 => coefficientPositivePacketRows088
  | 89 => coefficientPositivePacketRows089
  | 90 => coefficientPositivePacketRows090
  | 91 => coefficientPositivePacketRows091
  | 92 => coefficientPositivePacketRows092
  | 93 => coefficientPositivePacketRows093
  | 94 => coefficientPositivePacketRows094
  | 95 => coefficientPositivePacketRows095
  | 96 => coefficientPositivePacketRows096
  | 97 => coefficientPositivePacketRows097
  | 98 => coefficientPositivePacketRows098
  | 99 => coefficientPositivePacketRows099
  | 100 => coefficientPositivePacketRows100
  | 101 => coefficientPositivePacketRows101
  | 102 => coefficientPositivePacketRows102
  | 103 => coefficientPositivePacketRows103
  | 104 => coefficientPositivePacketRows104
  | 105 => coefficientPositivePacketRows105
  | 106 => coefficientPositivePacketRows106
  | 107 => coefficientPositivePacketRows107
  | 108 => coefficientPositivePacketRows108
  | 109 => coefficientPositivePacketRows109
  | 110 => coefficientPositivePacketRows110
  | 111 => coefficientPositivePacketRows111
  | 112 => coefficientPositivePacketRows112
  | 113 => coefficientPositivePacketRows113
  | 114 => coefficientPositivePacketRows114
  | 115 => coefficientPositivePacketRows115
  | 116 => coefficientPositivePacketRows116
  | 117 => coefficientPositivePacketRows117
  | 118 => coefficientPositivePacketRows118
  | 119 => coefficientPositivePacketRows119
  | 120 => coefficientPositivePacketRows120
  | 121 => coefficientPositivePacketRows121
  | 122 => coefficientPositivePacketRows122
  | 123 => coefficientPositivePacketRows123
  | 124 => coefficientPositivePacketRows124
  | 125 => coefficientPositivePacketRows125
  | 126 => coefficientPositivePacketRows126
  | 127 => coefficientPositivePacketRows127
  | 128 => coefficientPositivePacketRows128
  | 129 => coefficientPositivePacketRows129
  | 130 => coefficientPositivePacketRows130
  | 131 => coefficientPositivePacketRows131
  | 132 => coefficientPositivePacketRows132
  | 133 => coefficientPositivePacketRows133
  | 134 => coefficientPositivePacketRows134
  | 135 => coefficientPositivePacketRows135
  | 136 => coefficientPositivePacketRows136
  | 137 => coefficientPositivePacketRows137
  | 138 => coefficientPositivePacketRows138
  | 139 => coefficientPositivePacketRows139
  | 140 => coefficientPositivePacketRows140
  | 141 => coefficientPositivePacketRows141
  | 142 => coefficientPositivePacketRows142
  | 143 => coefficientPositivePacketRows143
  | 144 => coefficientPositivePacketRows144
  | 145 => coefficientPositivePacketRows145
  | 146 => coefficientPositivePacketRows146
  | 147 => coefficientPositivePacketRows147
  | 148 => coefficientPositivePacketRows148
  | 149 => coefficientPositivePacketRows149
  | 150 => coefficientPositivePacketRows150
  | 151 => coefficientPositivePacketRows151
  | 152 => coefficientPositivePacketRows152
  | 153 => coefficientPositivePacketRows153
  | 154 => coefficientPositivePacketRows154
  | 155 => coefficientPositivePacketRows155
  | 156 => coefficientPositivePacketRows156
  | 157 => coefficientPositivePacketRows157
  | 158 => coefficientPositivePacketRows158
  | 159 => coefficientPositivePacketRows159
  | 160 => coefficientPositivePacketRows160
  | 161 => coefficientPositivePacketRows161
  | 162 => coefficientPositivePacketRows162
  | 163 => coefficientPositivePacketRows163
  | 164 => coefficientPositivePacketRows164
  | 165 => coefficientPositivePacketRows165
  | 166 => coefficientPositivePacketRows166
  | 167 => coefficientPositivePacketRows167
  | 168 => coefficientPositivePacketRows168
  | 169 => coefficientPositivePacketRows169
  | 170 => coefficientPositivePacketRows170
  | 171 => coefficientPositivePacketRows171
  | 172 => coefficientPositivePacketRows172
  | 173 => coefficientPositivePacketRows173
  | 174 => coefficientPositivePacketRows174
  | 175 => coefficientPositivePacketRows175
  | 176 => coefficientPositivePacketRows176
  | 177 => coefficientPositivePacketRows177
  | 178 => coefficientPositivePacketRows178
  | 179 => coefficientPositivePacketRows179
  | 180 => coefficientPositivePacketRows180
  | 181 => coefficientPositivePacketRows181
  | 182 => coefficientPositivePacketRows182
  | 183 => coefficientPositivePacketRows183
  | 184 => coefficientPositivePacketRows184
  | 185 => coefficientPositivePacketRows185
  | 186 => coefficientPositivePacketRows186
  | 187 => coefficientPositivePacketRows187
  | 188 => coefficientPositivePacketRows188
  | 189 => coefficientPositivePacketRows189
  | 190 => coefficientPositivePacketRows190
  | 191 => coefficientPositivePacketRows191
  | 192 => coefficientPositivePacketRows192
  | 193 => coefficientPositivePacketRows193
  | 194 => coefficientPositivePacketRows194
  | 195 => coefficientPositivePacketRows195
  | 196 => coefficientPositivePacketRows196
  | 197 => coefficientPositivePacketRows197
  | 198 => coefficientPositivePacketRows198
  | 199 => coefficientPositivePacketRows199
  | 200 => coefficientPositivePacketRows200
  | 201 => coefficientPositivePacketRows201
  | 202 => coefficientPositivePacketRows202
  | 203 => coefficientPositivePacketRows203
  | 204 => coefficientPositivePacketRows204
  | 205 => coefficientPositivePacketRows205
  | 206 => coefficientPositivePacketRows206
  | 207 => coefficientPositivePacketRows207
  | 208 => coefficientPositivePacketRows208
  | 209 => coefficientPositivePacketRows209
  | 210 => coefficientPositivePacketRows210
  | 211 => coefficientPositivePacketRows211
  | 212 => coefficientPositivePacketRows212
  | 213 => coefficientPositivePacketRows213
  | 214 => coefficientPositivePacketRows214
  | 215 => coefficientPositivePacketRows215
  | 216 => coefficientPositivePacketRows216
  | 217 => coefficientPositivePacketRows217
  | 218 => coefficientPositivePacketRows218
  | 219 => coefficientPositivePacketRows219
  | 220 => coefficientPositivePacketRows220
  | 221 => coefficientPositivePacketRows221
  | 222 => coefficientPositivePacketRows222
  | 223 => coefficientPositivePacketRows223
  | 224 => coefficientPositivePacketRows224
  | 225 => coefficientPositivePacketRows225
  | 226 => coefficientPositivePacketRows226
  | 227 => coefficientPositivePacketRows227
  | 228 => coefficientPositivePacketRows228
  | 229 => coefficientPositivePacketRows229
  | 230 => coefficientPositivePacketRows230
  | 231 => coefficientPositivePacketRows231
  | 232 => coefficientPositivePacketRows232
  | 233 => coefficientPositivePacketRows233
  | 234 => coefficientPositivePacketRows234
  | 235 => coefficientPositivePacketRows235
  | 236 => coefficientPositivePacketRows236
  | 237 => coefficientPositivePacketRows237
  | 238 => coefficientPositivePacketRows238
  | 239 => coefficientPositivePacketRows239
  | 240 => coefficientPositivePacketRows240
  | 241 => coefficientPositivePacketRows241
  | 242 => coefficientPositivePacketRows242
  | 243 => coefficientPositivePacketRows243
  | 244 => coefficientPositivePacketRows244
  | 245 => coefficientPositivePacketRows245
  | 246 => coefficientPositivePacketRows246
  | 247 => coefficientPositivePacketRows247
  | 248 => coefficientPositivePacketRows248
  | 249 => coefficientPositivePacketRows249
  | 250 => coefficientPositivePacketRows250
  | 251 => coefficientPositivePacketRows251
  | 252 => coefficientPositivePacketRows252
  | 253 => coefficientPositivePacketRows253
  | 254 => coefficientPositivePacketRows254
  | 255 => coefficientPositivePacketRows255
  | 256 => coefficientPositivePacketRows256
  | 257 => coefficientPositivePacketRows257
  | 258 => coefficientPositivePacketRows258
  | 259 => coefficientPositivePacketRows259
  | 260 => coefficientPositivePacketRows260
  | 261 => coefficientPositivePacketRows261
  | 262 => coefficientPositivePacketRows262
  | 263 => coefficientPositivePacketRows263
  | 264 => coefficientPositivePacketRows264
  | 265 => coefficientPositivePacketRows265
  | 266 => coefficientPositivePacketRows266
  | _ => []


noncomputable def coefficientPositivePacketTermChunk : Nat → List (IntegerTableTerm 73033)
  | 0 => coefficientPositivePacketTerms000
  | 1 => coefficientPositivePacketTerms001
  | 2 => coefficientPositivePacketTerms002
  | 3 => coefficientPositivePacketTerms003
  | 4 => coefficientPositivePacketTerms004
  | 5 => coefficientPositivePacketTerms005
  | 6 => coefficientPositivePacketTerms006
  | 7 => coefficientPositivePacketTerms007
  | 8 => coefficientPositivePacketTerms008
  | 9 => coefficientPositivePacketTerms009
  | 10 => coefficientPositivePacketTerms010
  | 11 => coefficientPositivePacketTerms011
  | 12 => coefficientPositivePacketTerms012
  | 13 => coefficientPositivePacketTerms013
  | 14 => coefficientPositivePacketTerms014
  | 15 => coefficientPositivePacketTerms015
  | 16 => coefficientPositivePacketTerms016
  | 17 => coefficientPositivePacketTerms017
  | 18 => coefficientPositivePacketTerms018
  | 19 => coefficientPositivePacketTerms019
  | 20 => coefficientPositivePacketTerms020
  | 21 => coefficientPositivePacketTerms021
  | 22 => coefficientPositivePacketTerms022
  | 23 => coefficientPositivePacketTerms023
  | 24 => coefficientPositivePacketTerms024
  | 25 => coefficientPositivePacketTerms025
  | 26 => coefficientPositivePacketTerms026
  | 27 => coefficientPositivePacketTerms027
  | 28 => coefficientPositivePacketTerms028
  | 29 => coefficientPositivePacketTerms029
  | 30 => coefficientPositivePacketTerms030
  | 31 => coefficientPositivePacketTerms031
  | 32 => coefficientPositivePacketTerms032
  | 33 => coefficientPositivePacketTerms033
  | 34 => coefficientPositivePacketTerms034
  | 35 => coefficientPositivePacketTerms035
  | 36 => coefficientPositivePacketTerms036
  | 37 => coefficientPositivePacketTerms037
  | 38 => coefficientPositivePacketTerms038
  | 39 => coefficientPositivePacketTerms039
  | 40 => coefficientPositivePacketTerms040
  | 41 => coefficientPositivePacketTerms041
  | 42 => coefficientPositivePacketTerms042
  | 43 => coefficientPositivePacketTerms043
  | 44 => coefficientPositivePacketTerms044
  | 45 => coefficientPositivePacketTerms045
  | 46 => coefficientPositivePacketTerms046
  | 47 => coefficientPositivePacketTerms047
  | 48 => coefficientPositivePacketTerms048
  | 49 => coefficientPositivePacketTerms049
  | 50 => coefficientPositivePacketTerms050
  | 51 => coefficientPositivePacketTerms051
  | 52 => coefficientPositivePacketTerms052
  | 53 => coefficientPositivePacketTerms053
  | 54 => coefficientPositivePacketTerms054
  | 55 => coefficientPositivePacketTerms055
  | 56 => coefficientPositivePacketTerms056
  | 57 => coefficientPositivePacketTerms057
  | 58 => coefficientPositivePacketTerms058
  | 59 => coefficientPositivePacketTerms059
  | 60 => coefficientPositivePacketTerms060
  | 61 => coefficientPositivePacketTerms061
  | 62 => coefficientPositivePacketTerms062
  | 63 => coefficientPositivePacketTerms063
  | 64 => coefficientPositivePacketTerms064
  | 65 => coefficientPositivePacketTerms065
  | 66 => coefficientPositivePacketTerms066
  | 67 => coefficientPositivePacketTerms067
  | 68 => coefficientPositivePacketTerms068
  | 69 => coefficientPositivePacketTerms069
  | 70 => coefficientPositivePacketTerms070
  | 71 => coefficientPositivePacketTerms071
  | 72 => coefficientPositivePacketTerms072
  | 73 => coefficientPositivePacketTerms073
  | 74 => coefficientPositivePacketTerms074
  | 75 => coefficientPositivePacketTerms075
  | 76 => coefficientPositivePacketTerms076
  | 77 => coefficientPositivePacketTerms077
  | 78 => coefficientPositivePacketTerms078
  | 79 => coefficientPositivePacketTerms079
  | 80 => coefficientPositivePacketTerms080
  | 81 => coefficientPositivePacketTerms081
  | 82 => coefficientPositivePacketTerms082
  | 83 => coefficientPositivePacketTerms083
  | 84 => coefficientPositivePacketTerms084
  | 85 => coefficientPositivePacketTerms085
  | 86 => coefficientPositivePacketTerms086
  | 87 => coefficientPositivePacketTerms087
  | 88 => coefficientPositivePacketTerms088
  | 89 => coefficientPositivePacketTerms089
  | 90 => coefficientPositivePacketTerms090
  | 91 => coefficientPositivePacketTerms091
  | 92 => coefficientPositivePacketTerms092
  | 93 => coefficientPositivePacketTerms093
  | 94 => coefficientPositivePacketTerms094
  | 95 => coefficientPositivePacketTerms095
  | 96 => coefficientPositivePacketTerms096
  | 97 => coefficientPositivePacketTerms097
  | 98 => coefficientPositivePacketTerms098
  | 99 => coefficientPositivePacketTerms099
  | 100 => coefficientPositivePacketTerms100
  | 101 => coefficientPositivePacketTerms101
  | 102 => coefficientPositivePacketTerms102
  | 103 => coefficientPositivePacketTerms103
  | 104 => coefficientPositivePacketTerms104
  | 105 => coefficientPositivePacketTerms105
  | 106 => coefficientPositivePacketTerms106
  | 107 => coefficientPositivePacketTerms107
  | 108 => coefficientPositivePacketTerms108
  | 109 => coefficientPositivePacketTerms109
  | 110 => coefficientPositivePacketTerms110
  | 111 => coefficientPositivePacketTerms111
  | 112 => coefficientPositivePacketTerms112
  | 113 => coefficientPositivePacketTerms113
  | 114 => coefficientPositivePacketTerms114
  | 115 => coefficientPositivePacketTerms115
  | 116 => coefficientPositivePacketTerms116
  | 117 => coefficientPositivePacketTerms117
  | 118 => coefficientPositivePacketTerms118
  | 119 => coefficientPositivePacketTerms119
  | 120 => coefficientPositivePacketTerms120
  | 121 => coefficientPositivePacketTerms121
  | 122 => coefficientPositivePacketTerms122
  | 123 => coefficientPositivePacketTerms123
  | 124 => coefficientPositivePacketTerms124
  | 125 => coefficientPositivePacketTerms125
  | 126 => coefficientPositivePacketTerms126
  | 127 => coefficientPositivePacketTerms127
  | 128 => coefficientPositivePacketTerms128
  | 129 => coefficientPositivePacketTerms129
  | 130 => coefficientPositivePacketTerms130
  | 131 => coefficientPositivePacketTerms131
  | 132 => coefficientPositivePacketTerms132
  | 133 => coefficientPositivePacketTerms133
  | 134 => coefficientPositivePacketTerms134
  | 135 => coefficientPositivePacketTerms135
  | 136 => coefficientPositivePacketTerms136
  | 137 => coefficientPositivePacketTerms137
  | 138 => coefficientPositivePacketTerms138
  | 139 => coefficientPositivePacketTerms139
  | 140 => coefficientPositivePacketTerms140
  | 141 => coefficientPositivePacketTerms141
  | 142 => coefficientPositivePacketTerms142
  | 143 => coefficientPositivePacketTerms143
  | 144 => coefficientPositivePacketTerms144
  | 145 => coefficientPositivePacketTerms145
  | 146 => coefficientPositivePacketTerms146
  | 147 => coefficientPositivePacketTerms147
  | 148 => coefficientPositivePacketTerms148
  | 149 => coefficientPositivePacketTerms149
  | 150 => coefficientPositivePacketTerms150
  | 151 => coefficientPositivePacketTerms151
  | 152 => coefficientPositivePacketTerms152
  | 153 => coefficientPositivePacketTerms153
  | 154 => coefficientPositivePacketTerms154
  | 155 => coefficientPositivePacketTerms155
  | 156 => coefficientPositivePacketTerms156
  | 157 => coefficientPositivePacketTerms157
  | 158 => coefficientPositivePacketTerms158
  | 159 => coefficientPositivePacketTerms159
  | 160 => coefficientPositivePacketTerms160
  | 161 => coefficientPositivePacketTerms161
  | 162 => coefficientPositivePacketTerms162
  | 163 => coefficientPositivePacketTerms163
  | 164 => coefficientPositivePacketTerms164
  | 165 => coefficientPositivePacketTerms165
  | 166 => coefficientPositivePacketTerms166
  | 167 => coefficientPositivePacketTerms167
  | 168 => coefficientPositivePacketTerms168
  | 169 => coefficientPositivePacketTerms169
  | 170 => coefficientPositivePacketTerms170
  | 171 => coefficientPositivePacketTerms171
  | 172 => coefficientPositivePacketTerms172
  | 173 => coefficientPositivePacketTerms173
  | 174 => coefficientPositivePacketTerms174
  | 175 => coefficientPositivePacketTerms175
  | 176 => coefficientPositivePacketTerms176
  | 177 => coefficientPositivePacketTerms177
  | 178 => coefficientPositivePacketTerms178
  | 179 => coefficientPositivePacketTerms179
  | 180 => coefficientPositivePacketTerms180
  | 181 => coefficientPositivePacketTerms181
  | 182 => coefficientPositivePacketTerms182
  | 183 => coefficientPositivePacketTerms183
  | 184 => coefficientPositivePacketTerms184
  | 185 => coefficientPositivePacketTerms185
  | 186 => coefficientPositivePacketTerms186
  | 187 => coefficientPositivePacketTerms187
  | 188 => coefficientPositivePacketTerms188
  | 189 => coefficientPositivePacketTerms189
  | 190 => coefficientPositivePacketTerms190
  | 191 => coefficientPositivePacketTerms191
  | 192 => coefficientPositivePacketTerms192
  | 193 => coefficientPositivePacketTerms193
  | 194 => coefficientPositivePacketTerms194
  | 195 => coefficientPositivePacketTerms195
  | 196 => coefficientPositivePacketTerms196
  | 197 => coefficientPositivePacketTerms197
  | 198 => coefficientPositivePacketTerms198
  | 199 => coefficientPositivePacketTerms199
  | 200 => coefficientPositivePacketTerms200
  | 201 => coefficientPositivePacketTerms201
  | 202 => coefficientPositivePacketTerms202
  | 203 => coefficientPositivePacketTerms203
  | 204 => coefficientPositivePacketTerms204
  | 205 => coefficientPositivePacketTerms205
  | 206 => coefficientPositivePacketTerms206
  | 207 => coefficientPositivePacketTerms207
  | 208 => coefficientPositivePacketTerms208
  | 209 => coefficientPositivePacketTerms209
  | 210 => coefficientPositivePacketTerms210
  | 211 => coefficientPositivePacketTerms211
  | 212 => coefficientPositivePacketTerms212
  | 213 => coefficientPositivePacketTerms213
  | 214 => coefficientPositivePacketTerms214
  | 215 => coefficientPositivePacketTerms215
  | 216 => coefficientPositivePacketTerms216
  | 217 => coefficientPositivePacketTerms217
  | 218 => coefficientPositivePacketTerms218
  | 219 => coefficientPositivePacketTerms219
  | 220 => coefficientPositivePacketTerms220
  | 221 => coefficientPositivePacketTerms221
  | 222 => coefficientPositivePacketTerms222
  | 223 => coefficientPositivePacketTerms223
  | 224 => coefficientPositivePacketTerms224
  | 225 => coefficientPositivePacketTerms225
  | 226 => coefficientPositivePacketTerms226
  | 227 => coefficientPositivePacketTerms227
  | 228 => coefficientPositivePacketTerms228
  | 229 => coefficientPositivePacketTerms229
  | 230 => coefficientPositivePacketTerms230
  | 231 => coefficientPositivePacketTerms231
  | 232 => coefficientPositivePacketTerms232
  | 233 => coefficientPositivePacketTerms233
  | 234 => coefficientPositivePacketTerms234
  | 235 => coefficientPositivePacketTerms235
  | 236 => coefficientPositivePacketTerms236
  | 237 => coefficientPositivePacketTerms237
  | 238 => coefficientPositivePacketTerms238
  | 239 => coefficientPositivePacketTerms239
  | 240 => coefficientPositivePacketTerms240
  | 241 => coefficientPositivePacketTerms241
  | 242 => coefficientPositivePacketTerms242
  | 243 => coefficientPositivePacketTerms243
  | 244 => coefficientPositivePacketTerms244
  | 245 => coefficientPositivePacketTerms245
  | 246 => coefficientPositivePacketTerms246
  | 247 => coefficientPositivePacketTerms247
  | 248 => coefficientPositivePacketTerms248
  | 249 => coefficientPositivePacketTerms249
  | 250 => coefficientPositivePacketTerms250
  | 251 => coefficientPositivePacketTerms251
  | 252 => coefficientPositivePacketTerms252
  | 253 => coefficientPositivePacketTerms253
  | 254 => coefficientPositivePacketTerms254
  | 255 => coefficientPositivePacketTerms255
  | 256 => coefficientPositivePacketTerms256
  | 257 => coefficientPositivePacketTerms257
  | 258 => coefficientPositivePacketTerms258
  | 259 => coefficientPositivePacketTerms259
  | 260 => coefficientPositivePacketTerms260
  | 261 => coefficientPositivePacketTerms261
  | 262 => coefficientPositivePacketTerms262
  | 263 => coefficientPositivePacketTerms263
  | 264 => coefficientPositivePacketTerms264
  | 265 => coefficientPositivePacketTerms265
  | 266 => coefficientPositivePacketTerms266
  | _ => []

noncomputable def coefficientPositivePacketRowChunks : List (List (List Int)) :=
  (List.range 267).map coefficientPositivePacketRowChunk

noncomputable def coefficientPositivePacketTermChunks :
    List (List (IntegerTableTerm 73033)) :=
  (List.range 267).map coefficientPositivePacketTermChunk


noncomputable def coefficientDiagonalPacketRowChunk : Nat → List (List Int)
  | 0 => coefficientDiagonalPacketRows000
  | 1 => coefficientDiagonalPacketRows001
  | 2 => coefficientDiagonalPacketRows002
  | 3 => coefficientDiagonalPacketRows003
  | 4 => coefficientDiagonalPacketRows004
  | 5 => coefficientDiagonalPacketRows005
  | 6 => coefficientDiagonalPacketRows006
  | _ => []


noncomputable def coefficientDiagonalPacketTermChunk : Nat → List (IntegerTableTerm 73033)
  | 0 => coefficientDiagonalPacketTerms000
  | 1 => coefficientDiagonalPacketTerms001
  | 2 => coefficientDiagonalPacketTerms002
  | 3 => coefficientDiagonalPacketTerms003
  | 4 => coefficientDiagonalPacketTerms004
  | 5 => coefficientDiagonalPacketTerms005
  | 6 => coefficientDiagonalPacketTerms006
  | _ => []

noncomputable def coefficientDiagonalPacketRowChunks : List (List (List Int)) :=
  (List.range 7).map coefficientDiagonalPacketRowChunk

noncomputable def coefficientDiagonalPacketTermChunks :
    List (List (IntegerTableTerm 73033)) :=
  (List.range 7).map coefficientDiagonalPacketTermChunk

end AffineSymplecticCertificate

end ConnesRigidity
