
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch00
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch01
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch02
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch03
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch04
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch05
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch06
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch07
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch08
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch09
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch10
import ConnesRigidity.PropertyTExactCertificateOrbitCanonicalLexValidations.Batch11

namespace ConnesRigidity.AffineSymplecticOrbitCertificate

set_option maxRecDepth 1000000
set_option linter.style.setOption false

set_option maxHeartbeats 64000000 in

theorem coefficientCanonicalWitnessRowFastCheck_valid
    (orbit : Fin 995) :
    coefficientCanonicalWitnessRowFastCheck
      orbit.val symmetryData.toList
      (coefficientCanonicalWitnessData.getD orbit.val [])
      (coefficientRepresentativeData.getD orbit.val #[])
      (coefficientInverseRepresentativeData.getD orbit.val #[]) = true := by
  fin_cases orbit
  · exact coefficientCanonicalWitnessRowFastCheck_000
  · exact coefficientCanonicalWitnessRowFastCheck_001
  · exact coefficientCanonicalWitnessRowFastCheck_002
  · exact coefficientCanonicalWitnessRowFastCheck_003
  · exact coefficientCanonicalWitnessRowFastCheck_004
  · exact coefficientCanonicalWitnessRowFastCheck_005
  · exact coefficientCanonicalWitnessRowFastCheck_006
  · exact coefficientCanonicalWitnessRowFastCheck_007
  · exact coefficientCanonicalWitnessRowFastCheck_008
  · exact coefficientCanonicalWitnessRowFastCheck_009
  · exact coefficientCanonicalWitnessRowFastCheck_010
  · exact coefficientCanonicalWitnessRowFastCheck_011
  · exact coefficientCanonicalWitnessRowFastCheck_012
  · exact coefficientCanonicalWitnessRowFastCheck_013
  · exact coefficientCanonicalWitnessRowFastCheck_014
  · exact coefficientCanonicalWitnessRowFastCheck_015
  · exact coefficientCanonicalWitnessRowFastCheck_016
  · exact coefficientCanonicalWitnessRowFastCheck_017
  · exact coefficientCanonicalWitnessRowFastCheck_018
  · exact coefficientCanonicalWitnessRowFastCheck_019
  · exact coefficientCanonicalWitnessRowFastCheck_020
  · exact coefficientCanonicalWitnessRowFastCheck_021
  · exact coefficientCanonicalWitnessRowFastCheck_022
  · exact coefficientCanonicalWitnessRowFastCheck_023
  · exact coefficientCanonicalWitnessRowFastCheck_024
  · exact coefficientCanonicalWitnessRowFastCheck_025
  · exact coefficientCanonicalWitnessRowFastCheck_026
  · exact coefficientCanonicalWitnessRowFastCheck_027
  · exact coefficientCanonicalWitnessRowFastCheck_028
  · exact coefficientCanonicalWitnessRowFastCheck_029
  · exact coefficientCanonicalWitnessRowFastCheck_030
  · exact coefficientCanonicalWitnessRowFastCheck_031
  · exact coefficientCanonicalWitnessRowFastCheck_032
  · exact coefficientCanonicalWitnessRowFastCheck_033
  · exact coefficientCanonicalWitnessRowFastCheck_034
  · exact coefficientCanonicalWitnessRowFastCheck_035
  · exact coefficientCanonicalWitnessRowFastCheck_036
  · exact coefficientCanonicalWitnessRowFastCheck_037
  · exact coefficientCanonicalWitnessRowFastCheck_038
  · exact coefficientCanonicalWitnessRowFastCheck_039
  · exact coefficientCanonicalWitnessRowFastCheck_040
  · exact coefficientCanonicalWitnessRowFastCheck_041
  · exact coefficientCanonicalWitnessRowFastCheck_042
  · exact coefficientCanonicalWitnessRowFastCheck_043
  · exact coefficientCanonicalWitnessRowFastCheck_044
  · exact coefficientCanonicalWitnessRowFastCheck_045
  · exact coefficientCanonicalWitnessRowFastCheck_046
  · exact coefficientCanonicalWitnessRowFastCheck_047
  · exact coefficientCanonicalWitnessRowFastCheck_048
  · exact coefficientCanonicalWitnessRowFastCheck_049
  · exact coefficientCanonicalWitnessRowFastCheck_050
  · exact coefficientCanonicalWitnessRowFastCheck_051
  · exact coefficientCanonicalWitnessRowFastCheck_052
  · exact coefficientCanonicalWitnessRowFastCheck_053
  · exact coefficientCanonicalWitnessRowFastCheck_054
  · exact coefficientCanonicalWitnessRowFastCheck_055
  · exact coefficientCanonicalWitnessRowFastCheck_056
  · exact coefficientCanonicalWitnessRowFastCheck_057
  · exact coefficientCanonicalWitnessRowFastCheck_058
  · exact coefficientCanonicalWitnessRowFastCheck_059
  · exact coefficientCanonicalWitnessRowFastCheck_060
  · exact coefficientCanonicalWitnessRowFastCheck_061
  · exact coefficientCanonicalWitnessRowFastCheck_062
  · exact coefficientCanonicalWitnessRowFastCheck_063
  · exact coefficientCanonicalWitnessRowFastCheck_064
  · exact coefficientCanonicalWitnessRowFastCheck_065
  · exact coefficientCanonicalWitnessRowFastCheck_066
  · exact coefficientCanonicalWitnessRowFastCheck_067
  · exact coefficientCanonicalWitnessRowFastCheck_068
  · exact coefficientCanonicalWitnessRowFastCheck_069
  · exact coefficientCanonicalWitnessRowFastCheck_070
  · exact coefficientCanonicalWitnessRowFastCheck_071
  · exact coefficientCanonicalWitnessRowFastCheck_072
  · exact coefficientCanonicalWitnessRowFastCheck_073
  · exact coefficientCanonicalWitnessRowFastCheck_074
  · exact coefficientCanonicalWitnessRowFastCheck_075
  · exact coefficientCanonicalWitnessRowFastCheck_076
  · exact coefficientCanonicalWitnessRowFastCheck_077
  · exact coefficientCanonicalWitnessRowFastCheck_078
  · exact coefficientCanonicalWitnessRowFastCheck_079
  · exact coefficientCanonicalWitnessRowFastCheck_080
  · exact coefficientCanonicalWitnessRowFastCheck_081
  · exact coefficientCanonicalWitnessRowFastCheck_082
  · exact coefficientCanonicalWitnessRowFastCheck_083
  · exact coefficientCanonicalWitnessRowFastCheck_084
  · exact coefficientCanonicalWitnessRowFastCheck_085
  · exact coefficientCanonicalWitnessRowFastCheck_086
  · exact coefficientCanonicalWitnessRowFastCheck_087
  · exact coefficientCanonicalWitnessRowFastCheck_088
  · exact coefficientCanonicalWitnessRowFastCheck_089
  · exact coefficientCanonicalWitnessRowFastCheck_090
  · exact coefficientCanonicalWitnessRowFastCheck_091
  · exact coefficientCanonicalWitnessRowFastCheck_092
  · exact coefficientCanonicalWitnessRowFastCheck_093
  · exact coefficientCanonicalWitnessRowFastCheck_094
  · exact coefficientCanonicalWitnessRowFastCheck_095
  · exact coefficientCanonicalWitnessRowFastCheck_096
  · exact coefficientCanonicalWitnessRowFastCheck_097
  · exact coefficientCanonicalWitnessRowFastCheck_098
  · exact coefficientCanonicalWitnessRowFastCheck_099
  · exact coefficientCanonicalWitnessRowFastCheck_100
  · exact coefficientCanonicalWitnessRowFastCheck_101
  · exact coefficientCanonicalWitnessRowFastCheck_102
  · exact coefficientCanonicalWitnessRowFastCheck_103
  · exact coefficientCanonicalWitnessRowFastCheck_104
  · exact coefficientCanonicalWitnessRowFastCheck_105
  · exact coefficientCanonicalWitnessRowFastCheck_106
  · exact coefficientCanonicalWitnessRowFastCheck_107
  · exact coefficientCanonicalWitnessRowFastCheck_108
  · exact coefficientCanonicalWitnessRowFastCheck_109
  · exact coefficientCanonicalWitnessRowFastCheck_110
  · exact coefficientCanonicalWitnessRowFastCheck_111
  · exact coefficientCanonicalWitnessRowFastCheck_112
  · exact coefficientCanonicalWitnessRowFastCheck_113
  · exact coefficientCanonicalWitnessRowFastCheck_114
  · exact coefficientCanonicalWitnessRowFastCheck_115
  · exact coefficientCanonicalWitnessRowFastCheck_116
  · exact coefficientCanonicalWitnessRowFastCheck_117
  · exact coefficientCanonicalWitnessRowFastCheck_118
  · exact coefficientCanonicalWitnessRowFastCheck_119
  · exact coefficientCanonicalWitnessRowFastCheck_120
  · exact coefficientCanonicalWitnessRowFastCheck_121
  · exact coefficientCanonicalWitnessRowFastCheck_122
  · exact coefficientCanonicalWitnessRowFastCheck_123
  · exact coefficientCanonicalWitnessRowFastCheck_124
  · exact coefficientCanonicalWitnessRowFastCheck_125
  · exact coefficientCanonicalWitnessRowFastCheck_126
  · exact coefficientCanonicalWitnessRowFastCheck_127
  · exact coefficientCanonicalWitnessRowFastCheck_128
  · exact coefficientCanonicalWitnessRowFastCheck_129
  · exact coefficientCanonicalWitnessRowFastCheck_130
  · exact coefficientCanonicalWitnessRowFastCheck_131
  · exact coefficientCanonicalWitnessRowFastCheck_132
  · exact coefficientCanonicalWitnessRowFastCheck_133
  · exact coefficientCanonicalWitnessRowFastCheck_134
  · exact coefficientCanonicalWitnessRowFastCheck_135
  · exact coefficientCanonicalWitnessRowFastCheck_136
  · exact coefficientCanonicalWitnessRowFastCheck_137
  · exact coefficientCanonicalWitnessRowFastCheck_138
  · exact coefficientCanonicalWitnessRowFastCheck_139
  · exact coefficientCanonicalWitnessRowFastCheck_140
  · exact coefficientCanonicalWitnessRowFastCheck_141
  · exact coefficientCanonicalWitnessRowFastCheck_142
  · exact coefficientCanonicalWitnessRowFastCheck_143
  · exact coefficientCanonicalWitnessRowFastCheck_144
  · exact coefficientCanonicalWitnessRowFastCheck_145
  · exact coefficientCanonicalWitnessRowFastCheck_146
  · exact coefficientCanonicalWitnessRowFastCheck_147
  · exact coefficientCanonicalWitnessRowFastCheck_148
  · exact coefficientCanonicalWitnessRowFastCheck_149
  · exact coefficientCanonicalWitnessRowFastCheck_150
  · exact coefficientCanonicalWitnessRowFastCheck_151
  · exact coefficientCanonicalWitnessRowFastCheck_152
  · exact coefficientCanonicalWitnessRowFastCheck_153
  · exact coefficientCanonicalWitnessRowFastCheck_154
  · exact coefficientCanonicalWitnessRowFastCheck_155
  · exact coefficientCanonicalWitnessRowFastCheck_156
  · exact coefficientCanonicalWitnessRowFastCheck_157
  · exact coefficientCanonicalWitnessRowFastCheck_158
  · exact coefficientCanonicalWitnessRowFastCheck_159
  · exact coefficientCanonicalWitnessRowFastCheck_160
  · exact coefficientCanonicalWitnessRowFastCheck_161
  · exact coefficientCanonicalWitnessRowFastCheck_162
  · exact coefficientCanonicalWitnessRowFastCheck_163
  · exact coefficientCanonicalWitnessRowFastCheck_164
  · exact coefficientCanonicalWitnessRowFastCheck_165
  · exact coefficientCanonicalWitnessRowFastCheck_166
  · exact coefficientCanonicalWitnessRowFastCheck_167
  · exact coefficientCanonicalWitnessRowFastCheck_168
  · exact coefficientCanonicalWitnessRowFastCheck_169
  · exact coefficientCanonicalWitnessRowFastCheck_170
  · exact coefficientCanonicalWitnessRowFastCheck_171
  · exact coefficientCanonicalWitnessRowFastCheck_172
  · exact coefficientCanonicalWitnessRowFastCheck_173
  · exact coefficientCanonicalWitnessRowFastCheck_174
  · exact coefficientCanonicalWitnessRowFastCheck_175
  · exact coefficientCanonicalWitnessRowFastCheck_176
  · exact coefficientCanonicalWitnessRowFastCheck_177
  · exact coefficientCanonicalWitnessRowFastCheck_178
  · exact coefficientCanonicalWitnessRowFastCheck_179
  · exact coefficientCanonicalWitnessRowFastCheck_180
  · exact coefficientCanonicalWitnessRowFastCheck_181
  · exact coefficientCanonicalWitnessRowFastCheck_182
  · exact coefficientCanonicalWitnessRowFastCheck_183
  · exact coefficientCanonicalWitnessRowFastCheck_184
  · exact coefficientCanonicalWitnessRowFastCheck_185
  · exact coefficientCanonicalWitnessRowFastCheck_186
  · exact coefficientCanonicalWitnessRowFastCheck_187
  · exact coefficientCanonicalWitnessRowFastCheck_188
  · exact coefficientCanonicalWitnessRowFastCheck_189
  · exact coefficientCanonicalWitnessRowFastCheck_190
  · exact coefficientCanonicalWitnessRowFastCheck_191
  · exact coefficientCanonicalWitnessRowFastCheck_192
  · exact coefficientCanonicalWitnessRowFastCheck_193
  · exact coefficientCanonicalWitnessRowFastCheck_194
  · exact coefficientCanonicalWitnessRowFastCheck_195
  · exact coefficientCanonicalWitnessRowFastCheck_196
  · exact coefficientCanonicalWitnessRowFastCheck_197
  · exact coefficientCanonicalWitnessRowFastCheck_198
  · exact coefficientCanonicalWitnessRowFastCheck_199
  · exact coefficientCanonicalWitnessRowFastCheck_200
  · exact coefficientCanonicalWitnessRowFastCheck_201
  · exact coefficientCanonicalWitnessRowFastCheck_202
  · exact coefficientCanonicalWitnessRowFastCheck_203
  · exact coefficientCanonicalWitnessRowFastCheck_204
  · exact coefficientCanonicalWitnessRowFastCheck_205
  · exact coefficientCanonicalWitnessRowFastCheck_206
  · exact coefficientCanonicalWitnessRowFastCheck_207
  · exact coefficientCanonicalWitnessRowFastCheck_208
  · exact coefficientCanonicalWitnessRowFastCheck_209
  · exact coefficientCanonicalWitnessRowFastCheck_210
  · exact coefficientCanonicalWitnessRowFastCheck_211
  · exact coefficientCanonicalWitnessRowFastCheck_212
  · exact coefficientCanonicalWitnessRowFastCheck_213
  · exact coefficientCanonicalWitnessRowFastCheck_214
  · exact coefficientCanonicalWitnessRowFastCheck_215
  · exact coefficientCanonicalWitnessRowFastCheck_216
  · exact coefficientCanonicalWitnessRowFastCheck_217
  · exact coefficientCanonicalWitnessRowFastCheck_218
  · exact coefficientCanonicalWitnessRowFastCheck_219
  · exact coefficientCanonicalWitnessRowFastCheck_220
  · exact coefficientCanonicalWitnessRowFastCheck_221
  · exact coefficientCanonicalWitnessRowFastCheck_222
  · exact coefficientCanonicalWitnessRowFastCheck_223
  · exact coefficientCanonicalWitnessRowFastCheck_224
  · exact coefficientCanonicalWitnessRowFastCheck_225
  · exact coefficientCanonicalWitnessRowFastCheck_226
  · exact coefficientCanonicalWitnessRowFastCheck_227
  · exact coefficientCanonicalWitnessRowFastCheck_228
  · exact coefficientCanonicalWitnessRowFastCheck_229
  · exact coefficientCanonicalWitnessRowFastCheck_230
  · exact coefficientCanonicalWitnessRowFastCheck_231
  · exact coefficientCanonicalWitnessRowFastCheck_232
  · exact coefficientCanonicalWitnessRowFastCheck_233
  · exact coefficientCanonicalWitnessRowFastCheck_234
  · exact coefficientCanonicalWitnessRowFastCheck_235
  · exact coefficientCanonicalWitnessRowFastCheck_236
  · exact coefficientCanonicalWitnessRowFastCheck_237
  · exact coefficientCanonicalWitnessRowFastCheck_238
  · exact coefficientCanonicalWitnessRowFastCheck_239
  · exact coefficientCanonicalWitnessRowFastCheck_240
  · exact coefficientCanonicalWitnessRowFastCheck_241
  · exact coefficientCanonicalWitnessRowFastCheck_242
  · exact coefficientCanonicalWitnessRowFastCheck_243
  · exact coefficientCanonicalWitnessRowFastCheck_244
  · exact coefficientCanonicalWitnessRowFastCheck_245
  · exact coefficientCanonicalWitnessRowFastCheck_246
  · exact coefficientCanonicalWitnessRowFastCheck_247
  · exact coefficientCanonicalWitnessRowFastCheck_248
  · exact coefficientCanonicalWitnessRowFastCheck_249
  · exact coefficientCanonicalWitnessRowFastCheck_250
  · exact coefficientCanonicalWitnessRowFastCheck_251
  · exact coefficientCanonicalWitnessRowFastCheck_252
  · exact coefficientCanonicalWitnessRowFastCheck_253
  · exact coefficientCanonicalWitnessRowFastCheck_254
  · exact coefficientCanonicalWitnessRowFastCheck_255
  · exact coefficientCanonicalWitnessRowFastCheck_256
  · exact coefficientCanonicalWitnessRowFastCheck_257
  · exact coefficientCanonicalWitnessRowFastCheck_258
  · exact coefficientCanonicalWitnessRowFastCheck_259
  · exact coefficientCanonicalWitnessRowFastCheck_260
  · exact coefficientCanonicalWitnessRowFastCheck_261
  · exact coefficientCanonicalWitnessRowFastCheck_262
  · exact coefficientCanonicalWitnessRowFastCheck_263
  · exact coefficientCanonicalWitnessRowFastCheck_264
  · exact coefficientCanonicalWitnessRowFastCheck_265
  · exact coefficientCanonicalWitnessRowFastCheck_266
  · exact coefficientCanonicalWitnessRowFastCheck_267
  · exact coefficientCanonicalWitnessRowFastCheck_268
  · exact coefficientCanonicalWitnessRowFastCheck_269
  · exact coefficientCanonicalWitnessRowFastCheck_270
  · exact coefficientCanonicalWitnessRowFastCheck_271
  · exact coefficientCanonicalWitnessRowFastCheck_272
  · exact coefficientCanonicalWitnessRowFastCheck_273
  · exact coefficientCanonicalWitnessRowFastCheck_274
  · exact coefficientCanonicalWitnessRowFastCheck_275
  · exact coefficientCanonicalWitnessRowFastCheck_276
  · exact coefficientCanonicalWitnessRowFastCheck_277
  · exact coefficientCanonicalWitnessRowFastCheck_278
  · exact coefficientCanonicalWitnessRowFastCheck_279
  · exact coefficientCanonicalWitnessRowFastCheck_280
  · exact coefficientCanonicalWitnessRowFastCheck_281
  · exact coefficientCanonicalWitnessRowFastCheck_282
  · exact coefficientCanonicalWitnessRowFastCheck_283
  · exact coefficientCanonicalWitnessRowFastCheck_284
  · exact coefficientCanonicalWitnessRowFastCheck_285
  · exact coefficientCanonicalWitnessRowFastCheck_286
  · exact coefficientCanonicalWitnessRowFastCheck_287
  · exact coefficientCanonicalWitnessRowFastCheck_288
  · exact coefficientCanonicalWitnessRowFastCheck_289
  · exact coefficientCanonicalWitnessRowFastCheck_290
  · exact coefficientCanonicalWitnessRowFastCheck_291
  · exact coefficientCanonicalWitnessRowFastCheck_292
  · exact coefficientCanonicalWitnessRowFastCheck_293
  · exact coefficientCanonicalWitnessRowFastCheck_294
  · exact coefficientCanonicalWitnessRowFastCheck_295
  · exact coefficientCanonicalWitnessRowFastCheck_296
  · exact coefficientCanonicalWitnessRowFastCheck_297
  · exact coefficientCanonicalWitnessRowFastCheck_298
  · exact coefficientCanonicalWitnessRowFastCheck_299
  · exact coefficientCanonicalWitnessRowFastCheck_300
  · exact coefficientCanonicalWitnessRowFastCheck_301
  · exact coefficientCanonicalWitnessRowFastCheck_302
  · exact coefficientCanonicalWitnessRowFastCheck_303
  · exact coefficientCanonicalWitnessRowFastCheck_304
  · exact coefficientCanonicalWitnessRowFastCheck_305
  · exact coefficientCanonicalWitnessRowFastCheck_306
  · exact coefficientCanonicalWitnessRowFastCheck_307
  · exact coefficientCanonicalWitnessRowFastCheck_308
  · exact coefficientCanonicalWitnessRowFastCheck_309
  · exact coefficientCanonicalWitnessRowFastCheck_310
  · exact coefficientCanonicalWitnessRowFastCheck_311
  · exact coefficientCanonicalWitnessRowFastCheck_312
  · exact coefficientCanonicalWitnessRowFastCheck_313
  · exact coefficientCanonicalWitnessRowFastCheck_314
  · exact coefficientCanonicalWitnessRowFastCheck_315
  · exact coefficientCanonicalWitnessRowFastCheck_316
  · exact coefficientCanonicalWitnessRowFastCheck_317
  · exact coefficientCanonicalWitnessRowFastCheck_318
  · exact coefficientCanonicalWitnessRowFastCheck_319
  · exact coefficientCanonicalWitnessRowFastCheck_320
  · exact coefficientCanonicalWitnessRowFastCheck_321
  · exact coefficientCanonicalWitnessRowFastCheck_322
  · exact coefficientCanonicalWitnessRowFastCheck_323
  · exact coefficientCanonicalWitnessRowFastCheck_324
  · exact coefficientCanonicalWitnessRowFastCheck_325
  · exact coefficientCanonicalWitnessRowFastCheck_326
  · exact coefficientCanonicalWitnessRowFastCheck_327
  · exact coefficientCanonicalWitnessRowFastCheck_328
  · exact coefficientCanonicalWitnessRowFastCheck_329
  · exact coefficientCanonicalWitnessRowFastCheck_330
  · exact coefficientCanonicalWitnessRowFastCheck_331
  · exact coefficientCanonicalWitnessRowFastCheck_332
  · exact coefficientCanonicalWitnessRowFastCheck_333
  · exact coefficientCanonicalWitnessRowFastCheck_334
  · exact coefficientCanonicalWitnessRowFastCheck_335
  · exact coefficientCanonicalWitnessRowFastCheck_336
  · exact coefficientCanonicalWitnessRowFastCheck_337
  · exact coefficientCanonicalWitnessRowFastCheck_338
  · exact coefficientCanonicalWitnessRowFastCheck_339
  · exact coefficientCanonicalWitnessRowFastCheck_340
  · exact coefficientCanonicalWitnessRowFastCheck_341
  · exact coefficientCanonicalWitnessRowFastCheck_342
  · exact coefficientCanonicalWitnessRowFastCheck_343
  · exact coefficientCanonicalWitnessRowFastCheck_344
  · exact coefficientCanonicalWitnessRowFastCheck_345
  · exact coefficientCanonicalWitnessRowFastCheck_346
  · exact coefficientCanonicalWitnessRowFastCheck_347
  · exact coefficientCanonicalWitnessRowFastCheck_348
  · exact coefficientCanonicalWitnessRowFastCheck_349
  · exact coefficientCanonicalWitnessRowFastCheck_350
  · exact coefficientCanonicalWitnessRowFastCheck_351
  · exact coefficientCanonicalWitnessRowFastCheck_352
  · exact coefficientCanonicalWitnessRowFastCheck_353
  · exact coefficientCanonicalWitnessRowFastCheck_354
  · exact coefficientCanonicalWitnessRowFastCheck_355
  · exact coefficientCanonicalWitnessRowFastCheck_356
  · exact coefficientCanonicalWitnessRowFastCheck_357
  · exact coefficientCanonicalWitnessRowFastCheck_358
  · exact coefficientCanonicalWitnessRowFastCheck_359
  · exact coefficientCanonicalWitnessRowFastCheck_360
  · exact coefficientCanonicalWitnessRowFastCheck_361
  · exact coefficientCanonicalWitnessRowFastCheck_362
  · exact coefficientCanonicalWitnessRowFastCheck_363
  · exact coefficientCanonicalWitnessRowFastCheck_364
  · exact coefficientCanonicalWitnessRowFastCheck_365
  · exact coefficientCanonicalWitnessRowFastCheck_366
  · exact coefficientCanonicalWitnessRowFastCheck_367
  · exact coefficientCanonicalWitnessRowFastCheck_368
  · exact coefficientCanonicalWitnessRowFastCheck_369
  · exact coefficientCanonicalWitnessRowFastCheck_370
  · exact coefficientCanonicalWitnessRowFastCheck_371
  · exact coefficientCanonicalWitnessRowFastCheck_372
  · exact coefficientCanonicalWitnessRowFastCheck_373
  · exact coefficientCanonicalWitnessRowFastCheck_374
  · exact coefficientCanonicalWitnessRowFastCheck_375
  · exact coefficientCanonicalWitnessRowFastCheck_376
  · exact coefficientCanonicalWitnessRowFastCheck_377
  · exact coefficientCanonicalWitnessRowFastCheck_378
  · exact coefficientCanonicalWitnessRowFastCheck_379
  · exact coefficientCanonicalWitnessRowFastCheck_380
  · exact coefficientCanonicalWitnessRowFastCheck_381
  · exact coefficientCanonicalWitnessRowFastCheck_382
  · exact coefficientCanonicalWitnessRowFastCheck_383
  · exact coefficientCanonicalWitnessRowFastCheck_384
  · exact coefficientCanonicalWitnessRowFastCheck_385
  · exact coefficientCanonicalWitnessRowFastCheck_386
  · exact coefficientCanonicalWitnessRowFastCheck_387
  · exact coefficientCanonicalWitnessRowFastCheck_388
  · exact coefficientCanonicalWitnessRowFastCheck_389
  · exact coefficientCanonicalWitnessRowFastCheck_390
  · exact coefficientCanonicalWitnessRowFastCheck_391
  · exact coefficientCanonicalWitnessRowFastCheck_392
  · exact coefficientCanonicalWitnessRowFastCheck_393
  · exact coefficientCanonicalWitnessRowFastCheck_394
  · exact coefficientCanonicalWitnessRowFastCheck_395
  · exact coefficientCanonicalWitnessRowFastCheck_396
  · exact coefficientCanonicalWitnessRowFastCheck_397
  · exact coefficientCanonicalWitnessRowFastCheck_398
  · exact coefficientCanonicalWitnessRowFastCheck_399
  · exact coefficientCanonicalWitnessRowFastCheck_400
  · exact coefficientCanonicalWitnessRowFastCheck_401
  · exact coefficientCanonicalWitnessRowFastCheck_402
  · exact coefficientCanonicalWitnessRowFastCheck_403
  · exact coefficientCanonicalWitnessRowFastCheck_404
  · exact coefficientCanonicalWitnessRowFastCheck_405
  · exact coefficientCanonicalWitnessRowFastCheck_406
  · exact coefficientCanonicalWitnessRowFastCheck_407
  · exact coefficientCanonicalWitnessRowFastCheck_408
  · exact coefficientCanonicalWitnessRowFastCheck_409
  · exact coefficientCanonicalWitnessRowFastCheck_410
  · exact coefficientCanonicalWitnessRowFastCheck_411
  · exact coefficientCanonicalWitnessRowFastCheck_412
  · exact coefficientCanonicalWitnessRowFastCheck_413
  · exact coefficientCanonicalWitnessRowFastCheck_414
  · exact coefficientCanonicalWitnessRowFastCheck_415
  · exact coefficientCanonicalWitnessRowFastCheck_416
  · exact coefficientCanonicalWitnessRowFastCheck_417
  · exact coefficientCanonicalWitnessRowFastCheck_418
  · exact coefficientCanonicalWitnessRowFastCheck_419
  · exact coefficientCanonicalWitnessRowFastCheck_420
  · exact coefficientCanonicalWitnessRowFastCheck_421
  · exact coefficientCanonicalWitnessRowFastCheck_422
  · exact coefficientCanonicalWitnessRowFastCheck_423
  · exact coefficientCanonicalWitnessRowFastCheck_424
  · exact coefficientCanonicalWitnessRowFastCheck_425
  · exact coefficientCanonicalWitnessRowFastCheck_426
  · exact coefficientCanonicalWitnessRowFastCheck_427
  · exact coefficientCanonicalWitnessRowFastCheck_428
  · exact coefficientCanonicalWitnessRowFastCheck_429
  · exact coefficientCanonicalWitnessRowFastCheck_430
  · exact coefficientCanonicalWitnessRowFastCheck_431
  · exact coefficientCanonicalWitnessRowFastCheck_432
  · exact coefficientCanonicalWitnessRowFastCheck_433
  · exact coefficientCanonicalWitnessRowFastCheck_434
  · exact coefficientCanonicalWitnessRowFastCheck_435
  · exact coefficientCanonicalWitnessRowFastCheck_436
  · exact coefficientCanonicalWitnessRowFastCheck_437
  · exact coefficientCanonicalWitnessRowFastCheck_438
  · exact coefficientCanonicalWitnessRowFastCheck_439
  · exact coefficientCanonicalWitnessRowFastCheck_440
  · exact coefficientCanonicalWitnessRowFastCheck_441
  · exact coefficientCanonicalWitnessRowFastCheck_442
  · exact coefficientCanonicalWitnessRowFastCheck_443
  · exact coefficientCanonicalWitnessRowFastCheck_444
  · exact coefficientCanonicalWitnessRowFastCheck_445
  · exact coefficientCanonicalWitnessRowFastCheck_446
  · exact coefficientCanonicalWitnessRowFastCheck_447
  · exact coefficientCanonicalWitnessRowFastCheck_448
  · exact coefficientCanonicalWitnessRowFastCheck_449
  · exact coefficientCanonicalWitnessRowFastCheck_450
  · exact coefficientCanonicalWitnessRowFastCheck_451
  · exact coefficientCanonicalWitnessRowFastCheck_452
  · exact coefficientCanonicalWitnessRowFastCheck_453
  · exact coefficientCanonicalWitnessRowFastCheck_454
  · exact coefficientCanonicalWitnessRowFastCheck_455
  · exact coefficientCanonicalWitnessRowFastCheck_456
  · exact coefficientCanonicalWitnessRowFastCheck_457
  · exact coefficientCanonicalWitnessRowFastCheck_458
  · exact coefficientCanonicalWitnessRowFastCheck_459
  · exact coefficientCanonicalWitnessRowFastCheck_460
  · exact coefficientCanonicalWitnessRowFastCheck_461
  · exact coefficientCanonicalWitnessRowFastCheck_462
  · exact coefficientCanonicalWitnessRowFastCheck_463
  · exact coefficientCanonicalWitnessRowFastCheck_464
  · exact coefficientCanonicalWitnessRowFastCheck_465
  · exact coefficientCanonicalWitnessRowFastCheck_466
  · exact coefficientCanonicalWitnessRowFastCheck_467
  · exact coefficientCanonicalWitnessRowFastCheck_468
  · exact coefficientCanonicalWitnessRowFastCheck_469
  · exact coefficientCanonicalWitnessRowFastCheck_470
  · exact coefficientCanonicalWitnessRowFastCheck_471
  · exact coefficientCanonicalWitnessRowFastCheck_472
  · exact coefficientCanonicalWitnessRowFastCheck_473
  · exact coefficientCanonicalWitnessRowFastCheck_474
  · exact coefficientCanonicalWitnessRowFastCheck_475
  · exact coefficientCanonicalWitnessRowFastCheck_476
  · exact coefficientCanonicalWitnessRowFastCheck_477
  · exact coefficientCanonicalWitnessRowFastCheck_478
  · exact coefficientCanonicalWitnessRowFastCheck_479
  · exact coefficientCanonicalWitnessRowFastCheck_480
  · exact coefficientCanonicalWitnessRowFastCheck_481
  · exact coefficientCanonicalWitnessRowFastCheck_482
  · exact coefficientCanonicalWitnessRowFastCheck_483
  · exact coefficientCanonicalWitnessRowFastCheck_484
  · exact coefficientCanonicalWitnessRowFastCheck_485
  · exact coefficientCanonicalWitnessRowFastCheck_486
  · exact coefficientCanonicalWitnessRowFastCheck_487
  · exact coefficientCanonicalWitnessRowFastCheck_488
  · exact coefficientCanonicalWitnessRowFastCheck_489
  · exact coefficientCanonicalWitnessRowFastCheck_490
  · exact coefficientCanonicalWitnessRowFastCheck_491
  · exact coefficientCanonicalWitnessRowFastCheck_492
  · exact coefficientCanonicalWitnessRowFastCheck_493
  · exact coefficientCanonicalWitnessRowFastCheck_494
  · exact coefficientCanonicalWitnessRowFastCheck_495
  · exact coefficientCanonicalWitnessRowFastCheck_496
  · exact coefficientCanonicalWitnessRowFastCheck_497
  · exact coefficientCanonicalWitnessRowFastCheck_498
  · exact coefficientCanonicalWitnessRowFastCheck_499
  · exact coefficientCanonicalWitnessRowFastCheck_500
  · exact coefficientCanonicalWitnessRowFastCheck_501
  · exact coefficientCanonicalWitnessRowFastCheck_502
  · exact coefficientCanonicalWitnessRowFastCheck_503
  · exact coefficientCanonicalWitnessRowFastCheck_504
  · exact coefficientCanonicalWitnessRowFastCheck_505
  · exact coefficientCanonicalWitnessRowFastCheck_506
  · exact coefficientCanonicalWitnessRowFastCheck_507
  · exact coefficientCanonicalWitnessRowFastCheck_508
  · exact coefficientCanonicalWitnessRowFastCheck_509
  · exact coefficientCanonicalWitnessRowFastCheck_510
  · exact coefficientCanonicalWitnessRowFastCheck_511
  · exact coefficientCanonicalWitnessRowFastCheck_512
  · exact coefficientCanonicalWitnessRowFastCheck_513
  · exact coefficientCanonicalWitnessRowFastCheck_514
  · exact coefficientCanonicalWitnessRowFastCheck_515
  · exact coefficientCanonicalWitnessRowFastCheck_516
  · exact coefficientCanonicalWitnessRowFastCheck_517
  · exact coefficientCanonicalWitnessRowFastCheck_518
  · exact coefficientCanonicalWitnessRowFastCheck_519
  · exact coefficientCanonicalWitnessRowFastCheck_520
  · exact coefficientCanonicalWitnessRowFastCheck_521
  · exact coefficientCanonicalWitnessRowFastCheck_522
  · exact coefficientCanonicalWitnessRowFastCheck_523
  · exact coefficientCanonicalWitnessRowFastCheck_524
  · exact coefficientCanonicalWitnessRowFastCheck_525
  · exact coefficientCanonicalWitnessRowFastCheck_526
  · exact coefficientCanonicalWitnessRowFastCheck_527
  · exact coefficientCanonicalWitnessRowFastCheck_528
  · exact coefficientCanonicalWitnessRowFastCheck_529
  · exact coefficientCanonicalWitnessRowFastCheck_530
  · exact coefficientCanonicalWitnessRowFastCheck_531
  · exact coefficientCanonicalWitnessRowFastCheck_532
  · exact coefficientCanonicalWitnessRowFastCheck_533
  · exact coefficientCanonicalWitnessRowFastCheck_534
  · exact coefficientCanonicalWitnessRowFastCheck_535
  · exact coefficientCanonicalWitnessRowFastCheck_536
  · exact coefficientCanonicalWitnessRowFastCheck_537
  · exact coefficientCanonicalWitnessRowFastCheck_538
  · exact coefficientCanonicalWitnessRowFastCheck_539
  · exact coefficientCanonicalWitnessRowFastCheck_540
  · exact coefficientCanonicalWitnessRowFastCheck_541
  · exact coefficientCanonicalWitnessRowFastCheck_542
  · exact coefficientCanonicalWitnessRowFastCheck_543
  · exact coefficientCanonicalWitnessRowFastCheck_544
  · exact coefficientCanonicalWitnessRowFastCheck_545
  · exact coefficientCanonicalWitnessRowFastCheck_546
  · exact coefficientCanonicalWitnessRowFastCheck_547
  · exact coefficientCanonicalWitnessRowFastCheck_548
  · exact coefficientCanonicalWitnessRowFastCheck_549
  · exact coefficientCanonicalWitnessRowFastCheck_550
  · exact coefficientCanonicalWitnessRowFastCheck_551
  · exact coefficientCanonicalWitnessRowFastCheck_552
  · exact coefficientCanonicalWitnessRowFastCheck_553
  · exact coefficientCanonicalWitnessRowFastCheck_554
  · exact coefficientCanonicalWitnessRowFastCheck_555
  · exact coefficientCanonicalWitnessRowFastCheck_556
  · exact coefficientCanonicalWitnessRowFastCheck_557
  · exact coefficientCanonicalWitnessRowFastCheck_558
  · exact coefficientCanonicalWitnessRowFastCheck_559
  · exact coefficientCanonicalWitnessRowFastCheck_560
  · exact coefficientCanonicalWitnessRowFastCheck_561
  · exact coefficientCanonicalWitnessRowFastCheck_562
  · exact coefficientCanonicalWitnessRowFastCheck_563
  · exact coefficientCanonicalWitnessRowFastCheck_564
  · exact coefficientCanonicalWitnessRowFastCheck_565
  · exact coefficientCanonicalWitnessRowFastCheck_566
  · exact coefficientCanonicalWitnessRowFastCheck_567
  · exact coefficientCanonicalWitnessRowFastCheck_568
  · exact coefficientCanonicalWitnessRowFastCheck_569
  · exact coefficientCanonicalWitnessRowFastCheck_570
  · exact coefficientCanonicalWitnessRowFastCheck_571
  · exact coefficientCanonicalWitnessRowFastCheck_572
  · exact coefficientCanonicalWitnessRowFastCheck_573
  · exact coefficientCanonicalWitnessRowFastCheck_574
  · exact coefficientCanonicalWitnessRowFastCheck_575
  · exact coefficientCanonicalWitnessRowFastCheck_576
  · exact coefficientCanonicalWitnessRowFastCheck_577
  · exact coefficientCanonicalWitnessRowFastCheck_578
  · exact coefficientCanonicalWitnessRowFastCheck_579
  · exact coefficientCanonicalWitnessRowFastCheck_580
  · exact coefficientCanonicalWitnessRowFastCheck_581
  · exact coefficientCanonicalWitnessRowFastCheck_582
  · exact coefficientCanonicalWitnessRowFastCheck_583
  · exact coefficientCanonicalWitnessRowFastCheck_584
  · exact coefficientCanonicalWitnessRowFastCheck_585
  · exact coefficientCanonicalWitnessRowFastCheck_586
  · exact coefficientCanonicalWitnessRowFastCheck_587
  · exact coefficientCanonicalWitnessRowFastCheck_588
  · exact coefficientCanonicalWitnessRowFastCheck_589
  · exact coefficientCanonicalWitnessRowFastCheck_590
  · exact coefficientCanonicalWitnessRowFastCheck_591
  · exact coefficientCanonicalWitnessRowFastCheck_592
  · exact coefficientCanonicalWitnessRowFastCheck_593
  · exact coefficientCanonicalWitnessRowFastCheck_594
  · exact coefficientCanonicalWitnessRowFastCheck_595
  · exact coefficientCanonicalWitnessRowFastCheck_596
  · exact coefficientCanonicalWitnessRowFastCheck_597
  · exact coefficientCanonicalWitnessRowFastCheck_598
  · exact coefficientCanonicalWitnessRowFastCheck_599
  · exact coefficientCanonicalWitnessRowFastCheck_600
  · exact coefficientCanonicalWitnessRowFastCheck_601
  · exact coefficientCanonicalWitnessRowFastCheck_602
  · exact coefficientCanonicalWitnessRowFastCheck_603
  · exact coefficientCanonicalWitnessRowFastCheck_604
  · exact coefficientCanonicalWitnessRowFastCheck_605
  · exact coefficientCanonicalWitnessRowFastCheck_606
  · exact coefficientCanonicalWitnessRowFastCheck_607
  · exact coefficientCanonicalWitnessRowFastCheck_608
  · exact coefficientCanonicalWitnessRowFastCheck_609
  · exact coefficientCanonicalWitnessRowFastCheck_610
  · exact coefficientCanonicalWitnessRowFastCheck_611
  · exact coefficientCanonicalWitnessRowFastCheck_612
  · exact coefficientCanonicalWitnessRowFastCheck_613
  · exact coefficientCanonicalWitnessRowFastCheck_614
  · exact coefficientCanonicalWitnessRowFastCheck_615
  · exact coefficientCanonicalWitnessRowFastCheck_616
  · exact coefficientCanonicalWitnessRowFastCheck_617
  · exact coefficientCanonicalWitnessRowFastCheck_618
  · exact coefficientCanonicalWitnessRowFastCheck_619
  · exact coefficientCanonicalWitnessRowFastCheck_620
  · exact coefficientCanonicalWitnessRowFastCheck_621
  · exact coefficientCanonicalWitnessRowFastCheck_622
  · exact coefficientCanonicalWitnessRowFastCheck_623
  · exact coefficientCanonicalWitnessRowFastCheck_624
  · exact coefficientCanonicalWitnessRowFastCheck_625
  · exact coefficientCanonicalWitnessRowFastCheck_626
  · exact coefficientCanonicalWitnessRowFastCheck_627
  · exact coefficientCanonicalWitnessRowFastCheck_628
  · exact coefficientCanonicalWitnessRowFastCheck_629
  · exact coefficientCanonicalWitnessRowFastCheck_630
  · exact coefficientCanonicalWitnessRowFastCheck_631
  · exact coefficientCanonicalWitnessRowFastCheck_632
  · exact coefficientCanonicalWitnessRowFastCheck_633
  · exact coefficientCanonicalWitnessRowFastCheck_634
  · exact coefficientCanonicalWitnessRowFastCheck_635
  · exact coefficientCanonicalWitnessRowFastCheck_636
  · exact coefficientCanonicalWitnessRowFastCheck_637
  · exact coefficientCanonicalWitnessRowFastCheck_638
  · exact coefficientCanonicalWitnessRowFastCheck_639
  · exact coefficientCanonicalWitnessRowFastCheck_640
  · exact coefficientCanonicalWitnessRowFastCheck_641
  · exact coefficientCanonicalWitnessRowFastCheck_642
  · exact coefficientCanonicalWitnessRowFastCheck_643
  · exact coefficientCanonicalWitnessRowFastCheck_644
  · exact coefficientCanonicalWitnessRowFastCheck_645
  · exact coefficientCanonicalWitnessRowFastCheck_646
  · exact coefficientCanonicalWitnessRowFastCheck_647
  · exact coefficientCanonicalWitnessRowFastCheck_648
  · exact coefficientCanonicalWitnessRowFastCheck_649
  · exact coefficientCanonicalWitnessRowFastCheck_650
  · exact coefficientCanonicalWitnessRowFastCheck_651
  · exact coefficientCanonicalWitnessRowFastCheck_652
  · exact coefficientCanonicalWitnessRowFastCheck_653
  · exact coefficientCanonicalWitnessRowFastCheck_654
  · exact coefficientCanonicalWitnessRowFastCheck_655
  · exact coefficientCanonicalWitnessRowFastCheck_656
  · exact coefficientCanonicalWitnessRowFastCheck_657
  · exact coefficientCanonicalWitnessRowFastCheck_658
  · exact coefficientCanonicalWitnessRowFastCheck_659
  · exact coefficientCanonicalWitnessRowFastCheck_660
  · exact coefficientCanonicalWitnessRowFastCheck_661
  · exact coefficientCanonicalWitnessRowFastCheck_662
  · exact coefficientCanonicalWitnessRowFastCheck_663
  · exact coefficientCanonicalWitnessRowFastCheck_664
  · exact coefficientCanonicalWitnessRowFastCheck_665
  · exact coefficientCanonicalWitnessRowFastCheck_666
  · exact coefficientCanonicalWitnessRowFastCheck_667
  · exact coefficientCanonicalWitnessRowFastCheck_668
  · exact coefficientCanonicalWitnessRowFastCheck_669
  · exact coefficientCanonicalWitnessRowFastCheck_670
  · exact coefficientCanonicalWitnessRowFastCheck_671
  · exact coefficientCanonicalWitnessRowFastCheck_672
  · exact coefficientCanonicalWitnessRowFastCheck_673
  · exact coefficientCanonicalWitnessRowFastCheck_674
  · exact coefficientCanonicalWitnessRowFastCheck_675
  · exact coefficientCanonicalWitnessRowFastCheck_676
  · exact coefficientCanonicalWitnessRowFastCheck_677
  · exact coefficientCanonicalWitnessRowFastCheck_678
  · exact coefficientCanonicalWitnessRowFastCheck_679
  · exact coefficientCanonicalWitnessRowFastCheck_680
  · exact coefficientCanonicalWitnessRowFastCheck_681
  · exact coefficientCanonicalWitnessRowFastCheck_682
  · exact coefficientCanonicalWitnessRowFastCheck_683
  · exact coefficientCanonicalWitnessRowFastCheck_684
  · exact coefficientCanonicalWitnessRowFastCheck_685
  · exact coefficientCanonicalWitnessRowFastCheck_686
  · exact coefficientCanonicalWitnessRowFastCheck_687
  · exact coefficientCanonicalWitnessRowFastCheck_688
  · exact coefficientCanonicalWitnessRowFastCheck_689
  · exact coefficientCanonicalWitnessRowFastCheck_690
  · exact coefficientCanonicalWitnessRowFastCheck_691
  · exact coefficientCanonicalWitnessRowFastCheck_692
  · exact coefficientCanonicalWitnessRowFastCheck_693
  · exact coefficientCanonicalWitnessRowFastCheck_694
  · exact coefficientCanonicalWitnessRowFastCheck_695
  · exact coefficientCanonicalWitnessRowFastCheck_696
  · exact coefficientCanonicalWitnessRowFastCheck_697
  · exact coefficientCanonicalWitnessRowFastCheck_698
  · exact coefficientCanonicalWitnessRowFastCheck_699
  · exact coefficientCanonicalWitnessRowFastCheck_700
  · exact coefficientCanonicalWitnessRowFastCheck_701
  · exact coefficientCanonicalWitnessRowFastCheck_702
  · exact coefficientCanonicalWitnessRowFastCheck_703
  · exact coefficientCanonicalWitnessRowFastCheck_704
  · exact coefficientCanonicalWitnessRowFastCheck_705
  · exact coefficientCanonicalWitnessRowFastCheck_706
  · exact coefficientCanonicalWitnessRowFastCheck_707
  · exact coefficientCanonicalWitnessRowFastCheck_708
  · exact coefficientCanonicalWitnessRowFastCheck_709
  · exact coefficientCanonicalWitnessRowFastCheck_710
  · exact coefficientCanonicalWitnessRowFastCheck_711
  · exact coefficientCanonicalWitnessRowFastCheck_712
  · exact coefficientCanonicalWitnessRowFastCheck_713
  · exact coefficientCanonicalWitnessRowFastCheck_714
  · exact coefficientCanonicalWitnessRowFastCheck_715
  · exact coefficientCanonicalWitnessRowFastCheck_716
  · exact coefficientCanonicalWitnessRowFastCheck_717
  · exact coefficientCanonicalWitnessRowFastCheck_718
  · exact coefficientCanonicalWitnessRowFastCheck_719
  · exact coefficientCanonicalWitnessRowFastCheck_720
  · exact coefficientCanonicalWitnessRowFastCheck_721
  · exact coefficientCanonicalWitnessRowFastCheck_722
  · exact coefficientCanonicalWitnessRowFastCheck_723
  · exact coefficientCanonicalWitnessRowFastCheck_724
  · exact coefficientCanonicalWitnessRowFastCheck_725
  · exact coefficientCanonicalWitnessRowFastCheck_726
  · exact coefficientCanonicalWitnessRowFastCheck_727
  · exact coefficientCanonicalWitnessRowFastCheck_728
  · exact coefficientCanonicalWitnessRowFastCheck_729
  · exact coefficientCanonicalWitnessRowFastCheck_730
  · exact coefficientCanonicalWitnessRowFastCheck_731
  · exact coefficientCanonicalWitnessRowFastCheck_732
  · exact coefficientCanonicalWitnessRowFastCheck_733
  · exact coefficientCanonicalWitnessRowFastCheck_734
  · exact coefficientCanonicalWitnessRowFastCheck_735
  · exact coefficientCanonicalWitnessRowFastCheck_736
  · exact coefficientCanonicalWitnessRowFastCheck_737
  · exact coefficientCanonicalWitnessRowFastCheck_738
  · exact coefficientCanonicalWitnessRowFastCheck_739
  · exact coefficientCanonicalWitnessRowFastCheck_740
  · exact coefficientCanonicalWitnessRowFastCheck_741
  · exact coefficientCanonicalWitnessRowFastCheck_742
  · exact coefficientCanonicalWitnessRowFastCheck_743
  · exact coefficientCanonicalWitnessRowFastCheck_744
  · exact coefficientCanonicalWitnessRowFastCheck_745
  · exact coefficientCanonicalWitnessRowFastCheck_746
  · exact coefficientCanonicalWitnessRowFastCheck_747
  · exact coefficientCanonicalWitnessRowFastCheck_748
  · exact coefficientCanonicalWitnessRowFastCheck_749
  · exact coefficientCanonicalWitnessRowFastCheck_750
  · exact coefficientCanonicalWitnessRowFastCheck_751
  · exact coefficientCanonicalWitnessRowFastCheck_752
  · exact coefficientCanonicalWitnessRowFastCheck_753
  · exact coefficientCanonicalWitnessRowFastCheck_754
  · exact coefficientCanonicalWitnessRowFastCheck_755
  · exact coefficientCanonicalWitnessRowFastCheck_756
  · exact coefficientCanonicalWitnessRowFastCheck_757
  · exact coefficientCanonicalWitnessRowFastCheck_758
  · exact coefficientCanonicalWitnessRowFastCheck_759
  · exact coefficientCanonicalWitnessRowFastCheck_760
  · exact coefficientCanonicalWitnessRowFastCheck_761
  · exact coefficientCanonicalWitnessRowFastCheck_762
  · exact coefficientCanonicalWitnessRowFastCheck_763
  · exact coefficientCanonicalWitnessRowFastCheck_764
  · exact coefficientCanonicalWitnessRowFastCheck_765
  · exact coefficientCanonicalWitnessRowFastCheck_766
  · exact coefficientCanonicalWitnessRowFastCheck_767
  · exact coefficientCanonicalWitnessRowFastCheck_768
  · exact coefficientCanonicalWitnessRowFastCheck_769
  · exact coefficientCanonicalWitnessRowFastCheck_770
  · exact coefficientCanonicalWitnessRowFastCheck_771
  · exact coefficientCanonicalWitnessRowFastCheck_772
  · exact coefficientCanonicalWitnessRowFastCheck_773
  · exact coefficientCanonicalWitnessRowFastCheck_774
  · exact coefficientCanonicalWitnessRowFastCheck_775
  · exact coefficientCanonicalWitnessRowFastCheck_776
  · exact coefficientCanonicalWitnessRowFastCheck_777
  · exact coefficientCanonicalWitnessRowFastCheck_778
  · exact coefficientCanonicalWitnessRowFastCheck_779
  · exact coefficientCanonicalWitnessRowFastCheck_780
  · exact coefficientCanonicalWitnessRowFastCheck_781
  · exact coefficientCanonicalWitnessRowFastCheck_782
  · exact coefficientCanonicalWitnessRowFastCheck_783
  · exact coefficientCanonicalWitnessRowFastCheck_784
  · exact coefficientCanonicalWitnessRowFastCheck_785
  · exact coefficientCanonicalWitnessRowFastCheck_786
  · exact coefficientCanonicalWitnessRowFastCheck_787
  · exact coefficientCanonicalWitnessRowFastCheck_788
  · exact coefficientCanonicalWitnessRowFastCheck_789
  · exact coefficientCanonicalWitnessRowFastCheck_790
  · exact coefficientCanonicalWitnessRowFastCheck_791
  · exact coefficientCanonicalWitnessRowFastCheck_792
  · exact coefficientCanonicalWitnessRowFastCheck_793
  · exact coefficientCanonicalWitnessRowFastCheck_794
  · exact coefficientCanonicalWitnessRowFastCheck_795
  · exact coefficientCanonicalWitnessRowFastCheck_796
  · exact coefficientCanonicalWitnessRowFastCheck_797
  · exact coefficientCanonicalWitnessRowFastCheck_798
  · exact coefficientCanonicalWitnessRowFastCheck_799
  · exact coefficientCanonicalWitnessRowFastCheck_800
  · exact coefficientCanonicalWitnessRowFastCheck_801
  · exact coefficientCanonicalWitnessRowFastCheck_802
  · exact coefficientCanonicalWitnessRowFastCheck_803
  · exact coefficientCanonicalWitnessRowFastCheck_804
  · exact coefficientCanonicalWitnessRowFastCheck_805
  · exact coefficientCanonicalWitnessRowFastCheck_806
  · exact coefficientCanonicalWitnessRowFastCheck_807
  · exact coefficientCanonicalWitnessRowFastCheck_808
  · exact coefficientCanonicalWitnessRowFastCheck_809
  · exact coefficientCanonicalWitnessRowFastCheck_810
  · exact coefficientCanonicalWitnessRowFastCheck_811
  · exact coefficientCanonicalWitnessRowFastCheck_812
  · exact coefficientCanonicalWitnessRowFastCheck_813
  · exact coefficientCanonicalWitnessRowFastCheck_814
  · exact coefficientCanonicalWitnessRowFastCheck_815
  · exact coefficientCanonicalWitnessRowFastCheck_816
  · exact coefficientCanonicalWitnessRowFastCheck_817
  · exact coefficientCanonicalWitnessRowFastCheck_818
  · exact coefficientCanonicalWitnessRowFastCheck_819
  · exact coefficientCanonicalWitnessRowFastCheck_820
  · exact coefficientCanonicalWitnessRowFastCheck_821
  · exact coefficientCanonicalWitnessRowFastCheck_822
  · exact coefficientCanonicalWitnessRowFastCheck_823
  · exact coefficientCanonicalWitnessRowFastCheck_824
  · exact coefficientCanonicalWitnessRowFastCheck_825
  · exact coefficientCanonicalWitnessRowFastCheck_826
  · exact coefficientCanonicalWitnessRowFastCheck_827
  · exact coefficientCanonicalWitnessRowFastCheck_828
  · exact coefficientCanonicalWitnessRowFastCheck_829
  · exact coefficientCanonicalWitnessRowFastCheck_830
  · exact coefficientCanonicalWitnessRowFastCheck_831
  · exact coefficientCanonicalWitnessRowFastCheck_832
  · exact coefficientCanonicalWitnessRowFastCheck_833
  · exact coefficientCanonicalWitnessRowFastCheck_834
  · exact coefficientCanonicalWitnessRowFastCheck_835
  · exact coefficientCanonicalWitnessRowFastCheck_836
  · exact coefficientCanonicalWitnessRowFastCheck_837
  · exact coefficientCanonicalWitnessRowFastCheck_838
  · exact coefficientCanonicalWitnessRowFastCheck_839
  · exact coefficientCanonicalWitnessRowFastCheck_840
  · exact coefficientCanonicalWitnessRowFastCheck_841
  · exact coefficientCanonicalWitnessRowFastCheck_842
  · exact coefficientCanonicalWitnessRowFastCheck_843
  · exact coefficientCanonicalWitnessRowFastCheck_844
  · exact coefficientCanonicalWitnessRowFastCheck_845
  · exact coefficientCanonicalWitnessRowFastCheck_846
  · exact coefficientCanonicalWitnessRowFastCheck_847
  · exact coefficientCanonicalWitnessRowFastCheck_848
  · exact coefficientCanonicalWitnessRowFastCheck_849
  · exact coefficientCanonicalWitnessRowFastCheck_850
  · exact coefficientCanonicalWitnessRowFastCheck_851
  · exact coefficientCanonicalWitnessRowFastCheck_852
  · exact coefficientCanonicalWitnessRowFastCheck_853
  · exact coefficientCanonicalWitnessRowFastCheck_854
  · exact coefficientCanonicalWitnessRowFastCheck_855
  · exact coefficientCanonicalWitnessRowFastCheck_856
  · exact coefficientCanonicalWitnessRowFastCheck_857
  · exact coefficientCanonicalWitnessRowFastCheck_858
  · exact coefficientCanonicalWitnessRowFastCheck_859
  · exact coefficientCanonicalWitnessRowFastCheck_860
  · exact coefficientCanonicalWitnessRowFastCheck_861
  · exact coefficientCanonicalWitnessRowFastCheck_862
  · exact coefficientCanonicalWitnessRowFastCheck_863
  · exact coefficientCanonicalWitnessRowFastCheck_864
  · exact coefficientCanonicalWitnessRowFastCheck_865
  · exact coefficientCanonicalWitnessRowFastCheck_866
  · exact coefficientCanonicalWitnessRowFastCheck_867
  · exact coefficientCanonicalWitnessRowFastCheck_868
  · exact coefficientCanonicalWitnessRowFastCheck_869
  · exact coefficientCanonicalWitnessRowFastCheck_870
  · exact coefficientCanonicalWitnessRowFastCheck_871
  · exact coefficientCanonicalWitnessRowFastCheck_872
  · exact coefficientCanonicalWitnessRowFastCheck_873
  · exact coefficientCanonicalWitnessRowFastCheck_874
  · exact coefficientCanonicalWitnessRowFastCheck_875
  · exact coefficientCanonicalWitnessRowFastCheck_876
  · exact coefficientCanonicalWitnessRowFastCheck_877
  · exact coefficientCanonicalWitnessRowFastCheck_878
  · exact coefficientCanonicalWitnessRowFastCheck_879
  · exact coefficientCanonicalWitnessRowFastCheck_880
  · exact coefficientCanonicalWitnessRowFastCheck_881
  · exact coefficientCanonicalWitnessRowFastCheck_882
  · exact coefficientCanonicalWitnessRowFastCheck_883
  · exact coefficientCanonicalWitnessRowFastCheck_884
  · exact coefficientCanonicalWitnessRowFastCheck_885
  · exact coefficientCanonicalWitnessRowFastCheck_886
  · exact coefficientCanonicalWitnessRowFastCheck_887
  · exact coefficientCanonicalWitnessRowFastCheck_888
  · exact coefficientCanonicalWitnessRowFastCheck_889
  · exact coefficientCanonicalWitnessRowFastCheck_890
  · exact coefficientCanonicalWitnessRowFastCheck_891
  · exact coefficientCanonicalWitnessRowFastCheck_892
  · exact coefficientCanonicalWitnessRowFastCheck_893
  · exact coefficientCanonicalWitnessRowFastCheck_894
  · exact coefficientCanonicalWitnessRowFastCheck_895
  · exact coefficientCanonicalWitnessRowFastCheck_896
  · exact coefficientCanonicalWitnessRowFastCheck_897
  · exact coefficientCanonicalWitnessRowFastCheck_898
  · exact coefficientCanonicalWitnessRowFastCheck_899
  · exact coefficientCanonicalWitnessRowFastCheck_900
  · exact coefficientCanonicalWitnessRowFastCheck_901
  · exact coefficientCanonicalWitnessRowFastCheck_902
  · exact coefficientCanonicalWitnessRowFastCheck_903
  · exact coefficientCanonicalWitnessRowFastCheck_904
  · exact coefficientCanonicalWitnessRowFastCheck_905
  · exact coefficientCanonicalWitnessRowFastCheck_906
  · exact coefficientCanonicalWitnessRowFastCheck_907
  · exact coefficientCanonicalWitnessRowFastCheck_908
  · exact coefficientCanonicalWitnessRowFastCheck_909
  · exact coefficientCanonicalWitnessRowFastCheck_910
  · exact coefficientCanonicalWitnessRowFastCheck_911
  · exact coefficientCanonicalWitnessRowFastCheck_912
  · exact coefficientCanonicalWitnessRowFastCheck_913
  · exact coefficientCanonicalWitnessRowFastCheck_914
  · exact coefficientCanonicalWitnessRowFastCheck_915
  · exact coefficientCanonicalWitnessRowFastCheck_916
  · exact coefficientCanonicalWitnessRowFastCheck_917
  · exact coefficientCanonicalWitnessRowFastCheck_918
  · exact coefficientCanonicalWitnessRowFastCheck_919
  · exact coefficientCanonicalWitnessRowFastCheck_920
  · exact coefficientCanonicalWitnessRowFastCheck_921
  · exact coefficientCanonicalWitnessRowFastCheck_922
  · exact coefficientCanonicalWitnessRowFastCheck_923
  · exact coefficientCanonicalWitnessRowFastCheck_924
  · exact coefficientCanonicalWitnessRowFastCheck_925
  · exact coefficientCanonicalWitnessRowFastCheck_926
  · exact coefficientCanonicalWitnessRowFastCheck_927
  · exact coefficientCanonicalWitnessRowFastCheck_928
  · exact coefficientCanonicalWitnessRowFastCheck_929
  · exact coefficientCanonicalWitnessRowFastCheck_930
  · exact coefficientCanonicalWitnessRowFastCheck_931
  · exact coefficientCanonicalWitnessRowFastCheck_932
  · exact coefficientCanonicalWitnessRowFastCheck_933
  · exact coefficientCanonicalWitnessRowFastCheck_934
  · exact coefficientCanonicalWitnessRowFastCheck_935
  · exact coefficientCanonicalWitnessRowFastCheck_936
  · exact coefficientCanonicalWitnessRowFastCheck_937
  · exact coefficientCanonicalWitnessRowFastCheck_938
  · exact coefficientCanonicalWitnessRowFastCheck_939
  · exact coefficientCanonicalWitnessRowFastCheck_940
  · exact coefficientCanonicalWitnessRowFastCheck_941
  · exact coefficientCanonicalWitnessRowFastCheck_942
  · exact coefficientCanonicalWitnessRowFastCheck_943
  · exact coefficientCanonicalWitnessRowFastCheck_944
  · exact coefficientCanonicalWitnessRowFastCheck_945
  · exact coefficientCanonicalWitnessRowFastCheck_946
  · exact coefficientCanonicalWitnessRowFastCheck_947
  · exact coefficientCanonicalWitnessRowFastCheck_948
  · exact coefficientCanonicalWitnessRowFastCheck_949
  · exact coefficientCanonicalWitnessRowFastCheck_950
  · exact coefficientCanonicalWitnessRowFastCheck_951
  · exact coefficientCanonicalWitnessRowFastCheck_952
  · exact coefficientCanonicalWitnessRowFastCheck_953
  · exact coefficientCanonicalWitnessRowFastCheck_954
  · exact coefficientCanonicalWitnessRowFastCheck_955
  · exact coefficientCanonicalWitnessRowFastCheck_956
  · exact coefficientCanonicalWitnessRowFastCheck_957
  · exact coefficientCanonicalWitnessRowFastCheck_958
  · exact coefficientCanonicalWitnessRowFastCheck_959
  · exact coefficientCanonicalWitnessRowFastCheck_960
  · exact coefficientCanonicalWitnessRowFastCheck_961
  · exact coefficientCanonicalWitnessRowFastCheck_962
  · exact coefficientCanonicalWitnessRowFastCheck_963
  · exact coefficientCanonicalWitnessRowFastCheck_964
  · exact coefficientCanonicalWitnessRowFastCheck_965
  · exact coefficientCanonicalWitnessRowFastCheck_966
  · exact coefficientCanonicalWitnessRowFastCheck_967
  · exact coefficientCanonicalWitnessRowFastCheck_968
  · exact coefficientCanonicalWitnessRowFastCheck_969
  · exact coefficientCanonicalWitnessRowFastCheck_970
  · exact coefficientCanonicalWitnessRowFastCheck_971
  · exact coefficientCanonicalWitnessRowFastCheck_972
  · exact coefficientCanonicalWitnessRowFastCheck_973
  · exact coefficientCanonicalWitnessRowFastCheck_974
  · exact coefficientCanonicalWitnessRowFastCheck_975
  · exact coefficientCanonicalWitnessRowFastCheck_976
  · exact coefficientCanonicalWitnessRowFastCheck_977
  · exact coefficientCanonicalWitnessRowFastCheck_978
  · exact coefficientCanonicalWitnessRowFastCheck_979
  · exact coefficientCanonicalWitnessRowFastCheck_980
  · exact coefficientCanonicalWitnessRowFastCheck_981
  · exact coefficientCanonicalWitnessRowFastCheck_982
  · exact coefficientCanonicalWitnessRowFastCheck_983
  · exact coefficientCanonicalWitnessRowFastCheck_984
  · exact coefficientCanonicalWitnessRowFastCheck_985
  · exact coefficientCanonicalWitnessRowFastCheck_986
  · exact coefficientCanonicalWitnessRowFastCheck_987
  · exact coefficientCanonicalWitnessRowFastCheck_988
  · exact coefficientCanonicalWitnessRowFastCheck_989
  · exact coefficientCanonicalWitnessRowFastCheck_990
  · exact coefficientCanonicalWitnessRowFastCheck_991
  · exact coefficientCanonicalWitnessRowFastCheck_992
  · exact coefficientCanonicalWitnessRowFastCheck_993
  · exact coefficientCanonicalWitnessRowFastCheck_994

theorem coefficientCanonicalWitnessRowCheck_valid
    (orbit : Fin 995) :
    coefficientCanonicalWitnessRowCheck
      orbit.val symmetryData.toList
      (coefficientCanonicalWitnessData.getD orbit.val [])
      (coefficientRepresentativeData.getD orbit.val #[])
      (coefficientInverseRepresentativeData.getD orbit.val #[]) = true := by
  exact coefficientCanonicalWitnessRowFastCheck_sound _ _ _ _ _
    (coefficientCanonicalWitnessRowFastCheck_valid orbit)

end ConnesRigidity.AffineSymplecticOrbitCertificate
